export interface LocationOption {
  code: string;
  label: string;
}

const COUNTRIES: LocationOption[] = [
  { code: "US", label: "United States" },
  { code: "CA", label: "Canada" },
  { code: "GB", label: "United Kingdom" },
  { code: "AU", label: "Australia" },
  { code: "DE", label: "Germany" },
  { code: "FR", label: "France" },
  { code: "IN", label: "India" },
  { code: "JP", label: "Japan" },
  { code: "MX", label: "Mexico" },
  { code: "BR", label: "Brazil" },
  { code: "SG", label: "Singapore" },
  { code: "HK", label: "Hong Kong" },
  { code: "AE", label: "United Arab Emirates" },
  { code: "CH", label: "Switzerland" },
  { code: "IT", label: "Italy" },
  { code: "ES", label: "Spain" },
  { code: "NL", label: "Netherlands" },
  { code: "SE", label: "Sweden" },
  { code: "NO", label: "Norway" },
  { code: "DK", label: "Denmark" },
  { code: "FI", label: "Finland" },
  { code: "IE", label: "Ireland" },
  { code: "NZ", label: "New Zealand" },
  { code: "ZA", label: "South Africa" },
  { code: "KR", label: "South Korea" },
  { code: "CN", label: "China" },
  { code: "TW", label: "Taiwan" },
  { code: "PH", label: "Philippines" },
  { code: "TH", label: "Thailand" },
  { code: "MY", label: "Malaysia" },
  { code: "ID", label: "Indonesia" },
  { code: "VN", label: "Vietnam" },
  { code: "PK", label: "Pakistan" },
  { code: "BD", label: "Bangladesh" },
  { code: "NG", label: "Nigeria" },
  { code: "EG", label: "Egypt" },
  { code: "KE", label: "Kenya" },
  { code: "GH", label: "Ghana" },
  { code: "SA", label: "Saudi Arabia" },
  { code: "QA", label: "Qatar" },
  { code: "KW", label: "Kuwait" },
  { code: "BH", label: "Bahrain" },
  { code: "OM", label: "Oman" },
  { code: "JO", label: "Jordan" },
  { code: "LB", label: "Lebanon" },
  { code: "IL", label: "Israel" },
  { code: "TR", label: "Turkey" },
  { code: "PL", label: "Poland" },
  { code: "CZ", label: "Czech Republic" },
  { code: "AT", label: "Austria" },
  { code: "BE", label: "Belgium" },
  { code: "PT", label: "Portugal" },
  { code: "GR", label: "Greece" },
  { code: "RO", label: "Romania" },
  { code: "HU", label: "Hungary" },
  { code: "CO", label: "Colombia" },
  { code: "AR", label: "Argentina" },
  { code: "CL", label: "Chile" },
  { code: "PE", label: "Peru" },
  { code: "CR", label: "Costa Rica" },
  { code: "PA", label: "Panama" },
  { code: "DO", label: "Dominican Republic" },
  { code: "JM", label: "Jamaica" },
  { code: "TT", label: "Trinidad and Tobago" },
  { code: "OTHER", label: "Other" },
];

const STATES_BY_COUNTRY: Record<string, LocationOption[]> = {
  US: [
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware",
    "Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky",
    "Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi",
    "Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico",
    "New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
    "Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont",
    "Virginia","Washington","West Virginia","Wisconsin","Wyoming","District of Columbia",
  ].map((s) => ({ code: s, label: s })),

  CA: [
    { code: "AB", label: "Alberta" },
    { code: "BC", label: "British Columbia" },
    { code: "MB", label: "Manitoba" },
    { code: "NB", label: "New Brunswick" },
    { code: "NL", label: "Newfoundland and Labrador" },
    { code: "NS", label: "Nova Scotia" },
    { code: "NT", label: "Northwest Territories" },
    { code: "NU", label: "Nunavut" },
    { code: "ON", label: "Ontario" },
    { code: "PE", label: "Prince Edward Island" },
    { code: "QC", label: "Quebec" },
    { code: "SK", label: "Saskatchewan" },
    { code: "YT", label: "Yukon" },
  ],

  GB: [
    { code: "ENG", label: "England" },
    { code: "SCT", label: "Scotland" },
    { code: "WLS", label: "Wales" },
    { code: "NIR", label: "Northern Ireland" },
  ],

  AU: [
    { code: "NSW", label: "New South Wales" },
    { code: "VIC", label: "Victoria" },
    { code: "QLD", label: "Queensland" },
    { code: "WA", label: "Western Australia" },
    { code: "SA_AU", label: "South Australia" },
    { code: "TAS", label: "Tasmania" },
    { code: "ACT", label: "Australian Capital Territory" },
    { code: "NT_AU", label: "Northern Territory" },
  ],

  DE: [
    { code: "BW", label: "Baden-Württemberg" },
    { code: "BY", label: "Bavaria" },
    { code: "BE_DE", label: "Berlin" },
    { code: "BB", label: "Brandenburg" },
    { code: "HB", label: "Bremen" },
    { code: "HH", label: "Hamburg" },
    { code: "HE", label: "Hesse" },
    { code: "MV", label: "Mecklenburg-Vorpommern" },
    { code: "NI", label: "Lower Saxony" },
    { code: "NW", label: "North Rhine-Westphalia" },
    { code: "RP", label: "Rhineland-Palatinate" },
    { code: "SL", label: "Saarland" },
    { code: "SN", label: "Saxony" },
    { code: "ST", label: "Saxony-Anhalt" },
    { code: "SH", label: "Schleswig-Holstein" },
    { code: "TH", label: "Thuringia" },
  ],

  FR: [
    { code: "IDF", label: "Île-de-France" },
    { code: "ARA", label: "Auvergne-Rhône-Alpes" },
    { code: "HDF", label: "Hauts-de-France" },
    { code: "NAQ", label: "Nouvelle-Aquitaine" },
    { code: "OCC", label: "Occitanie" },
    { code: "PAC", label: "Provence-Alpes-Côte d'Azur" },
    { code: "GES", label: "Grand Est" },
    { code: "BRE", label: "Brittany" },
    { code: "NOR", label: "Normandy" },
    { code: "PDL", label: "Pays de la Loire" },
    { code: "CVL", label: "Centre-Val de Loire" },
    { code: "BFC", label: "Bourgogne-Franche-Comté" },
    { code: "COR", label: "Corsica" },
  ],

  IN: [
    { code: "AP", label: "Andhra Pradesh" },
    { code: "AR", label: "Arunachal Pradesh" },
    { code: "AS", label: "Assam" },
    { code: "BR_IN", label: "Bihar" },
    { code: "CG", label: "Chhattisgarh" },
    { code: "GA", label: "Goa" },
    { code: "GJ", label: "Gujarat" },
    { code: "HR", label: "Haryana" },
    { code: "HP", label: "Himachal Pradesh" },
    { code: "JH", label: "Jharkhand" },
    { code: "KA", label: "Karnataka" },
    { code: "KL", label: "Kerala" },
    { code: "MP", label: "Madhya Pradesh" },
    { code: "MH", label: "Maharashtra" },
    { code: "MN", label: "Manipur" },
    { code: "ML", label: "Meghalaya" },
    { code: "MZ_IN", label: "Mizoram" },
    { code: "NL_IN", label: "Nagaland" },
    { code: "OD", label: "Odisha" },
    { code: "PB", label: "Punjab" },
    { code: "RJ", label: "Rajasthan" },
    { code: "SK_IN", label: "Sikkim" },
    { code: "TN", label: "Tamil Nadu" },
    { code: "TS", label: "Telangana" },
    { code: "TR_IN", label: "Tripura" },
    { code: "UP", label: "Uttar Pradesh" },
    { code: "UK", label: "Uttarakhand" },
    { code: "WB", label: "West Bengal" },
    { code: "DL", label: "Delhi" },
  ],

  JP: [
    { code: "JP13", label: "Tokyo" },
    { code: "JP27", label: "Osaka" },
    { code: "JP23", label: "Aichi" },
    { code: "JP14", label: "Kanagawa" },
    { code: "JP11", label: "Saitama" },
    { code: "JP12", label: "Chiba" },
    { code: "JP01", label: "Hokkaido" },
    { code: "JP40", label: "Fukuoka" },
    { code: "JP26", label: "Kyoto" },
    { code: "JP28", label: "Hyogo" },
  ],

  MX: [
    { code: "AGU", label: "Aguascalientes" },
    { code: "BCN", label: "Baja California" },
    { code: "BCS", label: "Baja California Sur" },
    { code: "CHH", label: "Chihuahua" },
    { code: "CHP", label: "Chiapas" },
    { code: "CMX", label: "Ciudad de México" },
    { code: "COA", label: "Coahuila" },
    { code: "GUA", label: "Guanajuato" },
    { code: "GRO", label: "Guerrero" },
    { code: "JAL", label: "Jalisco" },
    { code: "MEX", label: "Estado de México" },
    { code: "MIC", label: "Michoacán" },
    { code: "NLE", label: "Nuevo León" },
    { code: "OAX", label: "Oaxaca" },
    { code: "PUE", label: "Puebla" },
    { code: "QUE", label: "Querétaro" },
    { code: "SIN", label: "Sinaloa" },
    { code: "SON", label: "Sonora" },
    { code: "TAB", label: "Tabasco" },
    { code: "VER", label: "Veracruz" },
    { code: "YUC", label: "Yucatán" },
  ],

  BR: [
    { code: "SP", label: "São Paulo" },
    { code: "RJ_BR", label: "Rio de Janeiro" },
    { code: "MG", label: "Minas Gerais" },
    { code: "BA", label: "Bahia" },
    { code: "RS", label: "Rio Grande do Sul" },
    { code: "PR", label: "Paraná" },
    { code: "PE_BR", label: "Pernambuco" },
    { code: "CE", label: "Ceará" },
    { code: "PA_BR", label: "Pará" },
    { code: "SC", label: "Santa Catarina" },
    { code: "GO", label: "Goiás" },
    { code: "DF", label: "Distrito Federal" },
    { code: "AM", label: "Amazonas" },
  ],

  IT: [
    { code: "LAZ", label: "Lazio" },
    { code: "LOM", label: "Lombardy" },
    { code: "CAM", label: "Campania" },
    { code: "SIC", label: "Sicily" },
    { code: "VEN", label: "Veneto" },
    { code: "PIE", label: "Piedmont" },
    { code: "EMR", label: "Emilia-Romagna" },
    { code: "TOS", label: "Tuscany" },
  ],

  ES: [
    { code: "MD", label: "Madrid" },
    { code: "CT", label: "Catalonia" },
    { code: "AN", label: "Andalusia" },
    { code: "VC", label: "Valencia" },
    { code: "GA_ES", label: "Galicia" },
    { code: "PV", label: "Basque Country" },
    { code: "CL_ES", label: "Castile and León" },
    { code: "CN_ES", label: "Canary Islands" },
  ],

  NL: [
    { code: "NH", label: "North Holland" },
    { code: "ZH", label: "South Holland" },
    { code: "NB_NL", label: "North Brabant" },
    { code: "GE", label: "Gelderland" },
    { code: "UT", label: "Utrecht" },
    { code: "OV", label: "Overijssel" },
    { code: "LI", label: "Limburg" },
  ],

  CH: [
    { code: "ZH_CH", label: "Zürich" },
    { code: "BE_CH", label: "Bern" },
    { code: "VD", label: "Vaud" },
    { code: "GE_CH", label: "Geneva" },
    { code: "LU_CH", label: "Lucerne" },
    { code: "BS", label: "Basel-Stadt" },
    { code: "TI", label: "Ticino" },
  ],

  AE: [
    { code: "AUH", label: "Abu Dhabi" },
    { code: "DXB", label: "Dubai" },
    { code: "SHJ", label: "Sharjah" },
    { code: "AJM", label: "Ajman" },
    { code: "RAK", label: "Ras al-Khaimah" },
    { code: "FUJ", label: "Fujairah" },
    { code: "UAQ", label: "Umm al-Quwain" },
  ],

  ZA: [
    { code: "GP", label: "Gauteng" },
    { code: "WC", label: "Western Cape" },
    { code: "KZN", label: "KwaZulu-Natal" },
    { code: "EC", label: "Eastern Cape" },
    { code: "MP_ZA", label: "Mpumalanga" },
    { code: "LP", label: "Limpopo" },
    { code: "NW_ZA", label: "North West" },
    { code: "FS", label: "Free State" },
    { code: "NC", label: "Northern Cape" },
  ],

  KR: [
    { code: "SEL", label: "Seoul" },
    { code: "PUS", label: "Busan" },
    { code: "ICN", label: "Incheon" },
    { code: "DGU", label: "Daegu" },
    { code: "DJN", label: "Daejeon" },
    { code: "GWJ", label: "Gwangju" },
    { code: "GGD", label: "Gyeonggi-do" },
  ],

  CN: [
    { code: "BJ", label: "Beijing" },
    { code: "SH_CN", label: "Shanghai" },
    { code: "GD", label: "Guangdong" },
    { code: "ZJ", label: "Zhejiang" },
    { code: "JS", label: "Jiangsu" },
    { code: "SD", label: "Shandong" },
    { code: "HEB", label: "Hebei" },
    { code: "SC_CN", label: "Sichuan" },
    { code: "FJ", label: "Fujian" },
    { code: "HN_CN", label: "Hunan" },
  ],

  NG: [
    { code: "LA", label: "Lagos" },
    { code: "ABJ", label: "Abuja (FCT)" },
    { code: "KN", label: "Kano" },
    { code: "RV", label: "Rivers" },
    { code: "OG", label: "Ogun" },
    { code: "OY", label: "Oyo" },
  ],

  PH: [
    { code: "NCR", label: "Metro Manila (NCR)" },
    { code: "CEB", label: "Cebu" },
    { code: "DVO", label: "Davao" },
    { code: "ILO", label: "Iloilo" },
    { code: "BUL", label: "Bulacan" },
    { code: "CAV", label: "Cavite" },
    { code: "LAG", label: "Laguna" },
  ],

  TR: [
    { code: "IST", label: "Istanbul" },
    { code: "ANK", label: "Ankara" },
    { code: "IZM", label: "Izmir" },
    { code: "ANT", label: "Antalya" },
    { code: "BRS", label: "Bursa" },
    { code: "ADN", label: "Adana" },
  ],

  PL: [
    { code: "MZ", label: "Masovia (Warsaw)" },
    { code: "ML_PL", label: "Lesser Poland" },
    { code: "WP", label: "Greater Poland" },
    { code: "DS", label: "Lower Silesia" },
    { code: "SL_PL", label: "Silesia" },
    { code: "PM", label: "Pomerania" },
  ],

  CO: [
    { code: "BOG", label: "Bogotá D.C." },
    { code: "ANT_CO", label: "Antioquia" },
    { code: "VAL", label: "Valle del Cauca" },
    { code: "ATL", label: "Atlántico" },
    { code: "SAN", label: "Santander" },
  ],

  AR: [
    { code: "CABA", label: "Buenos Aires (City)" },
    { code: "BA_AR", label: "Buenos Aires (Province)" },
    { code: "COR_AR", label: "Córdoba" },
    { code: "SFE", label: "Santa Fe" },
    { code: "MZA", label: "Mendoza" },
    { code: "TUC", label: "Tucumán" },
  ],

  NZ: [
    { code: "AKL", label: "Auckland" },
    { code: "WGN", label: "Wellington" },
    { code: "CAN", label: "Canterbury" },
    { code: "WKO", label: "Waikato" },
    { code: "BOP", label: "Bay of Plenty" },
    { code: "OTA", label: "Otago" },
  ],

  SA: [
    { code: "RYD", label: "Riyadh" },
    { code: "MKH", label: "Makkah" },
    { code: "ESH", label: "Eastern Province" },
    { code: "MDN", label: "Madinah" },
    { code: "ASR", label: "Asir" },
  ],

  IL: [
    { code: "TA", label: "Tel Aviv District" },
    { code: "JM", label: "Jerusalem District" },
    { code: "HFA", label: "Haifa District" },
    { code: "CTR", label: "Central District" },
    { code: "STH", label: "Southern District" },
    { code: "NTH", label: "Northern District" },
  ],

  SE: [
    { code: "STK", label: "Stockholm" },
    { code: "VGT", label: "Västra Götaland" },
    { code: "SKN", label: "Skåne" },
  ],

  NO: [
    { code: "OSL", label: "Oslo" },
    { code: "VKN", label: "Vestland" },
    { code: "TRO", label: "Trøndelag" },
  ],

  DK: [
    { code: "CPH", label: "Capital Region" },
    { code: "SDK", label: "Southern Denmark" },
    { code: "MDJ", label: "Central Jutland" },
  ],

  IE: [
    { code: "DUB", label: "Dublin" },
    { code: "CRK", label: "Cork" },
    { code: "GAL", label: "Galway" },
    { code: "LMK", label: "Limerick" },
  ],

  SG: [
    { code: "SG_C", label: "Central Region" },
    { code: "SG_N", label: "North Region" },
    { code: "SG_E", label: "East Region" },
    { code: "SG_W", label: "West Region" },
    { code: "SG_NE", label: "North-East Region" },
  ],

  HK: [
    { code: "HKI", label: "Hong Kong Island" },
    { code: "KLN", label: "Kowloon" },
    { code: "NTR", label: "New Territories" },
  ],
};

const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
  Alaska: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
  Arizona: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Gilbert", "Tempe"],
  Arkansas: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  California: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Anaheim", "Irvine", "Riverside", "Bakersfield", "Santa Ana", "Pasadena"],
  Colorado: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Boulder"],
  Connecticut: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury", "Norwalk"],
  Delaware: ["Wilmington", "Dover", "Newark", "Middletown"],
  "District of Columbia": ["Washington"],
  Florida: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Tallahassee", "Fort Lauderdale", "Cape Coral", "West Palm Beach", "Gainesville"],
  Georgia: ["Atlanta", "Columbus", "Augusta", "Macon", "Savannah", "Athens"],
  Hawaii: ["Honolulu", "Pearl City", "Hilo", "Kailua"],
  Idaho: ["Boise", "Nampa", "Meridian", "Idaho Falls", "Pocatello"],
  Illinois: ["Chicago", "Aurora", "Joliet", "Naperville", "Rockford", "Springfield"],
  Indiana: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
  Iowa: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
  Kansas: ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka"],
  Kentucky: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
  Louisiana: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  Maine: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  Maryland: ["Baltimore", "Rockville", "Frederick", "Gaithersburg", "Annapolis"],
  Massachusetts: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy"],
  Michigan: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint"],
  Minnesota: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
  Mississippi: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
  Missouri: ["Kansas City", "Saint Louis", "Springfield", "Columbia", "Independence"],
  Montana: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"],
  Nebraska: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  Nevada: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
  "New Hampshire": ["Manchester", "Nashua", "Concord", "Dover", "Rochester"],
  "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Toms River", "Trenton"],
  "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
  "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
  "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville"],
  "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  Ohio: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  Oklahoma: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton"],
  Oregon: ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro", "Bend"],
  Pennsylvania: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Harrisburg"],
  "Rhode Island": ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"],
  "South Carolina": ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Greenville"],
  "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
  Tennessee: ["Memphis", "Nashville", "Knoxville", "Chattanooga", "Clarksville"],
  Texas: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo"],
  Utah: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
  Vermont: ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
  Virginia: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Arlington"],
  Washington: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kirkland"],
  "West Virginia": ["Charleston", "Huntington", "Parkersburg", "Morgantown", "Wheeling"],
  Wisconsin: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
  Wyoming: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],

  AB: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "St. Albert", "Medicine Hat"],
  BC: ["Vancouver", "Surrey", "Burnaby", "Richmond", "Abbotsford", "Victoria", "Kelowna"],
  MB: ["Winnipeg", "Brandon", "Steinbach", "Thompson"],
  NB: ["Moncton", "Saint John", "Fredericton", "Miramichi"],
  NL: ["St. John's", "Mount Pearl", "Corner Brook", "Gander"],
  NS: ["Halifax", "Dartmouth", "Sydney", "Truro"],
  NT: ["Yellowknife", "Hay River", "Inuvik"],
  NU: ["Iqaluit", "Rankin Inlet"],
  ON: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor"],
  PE: ["Charlottetown", "Summerside", "Stratford"],
  QC: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke"],
  SK: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw"],
  YT: ["Whitehorse", "Dawson City"],

  ENG: ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Sheffield", "Bristol", "Newcastle", "Nottingham", "Leicester"],
  SCT: ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "Stirling"],
  WLS: ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor"],
  NIR: ["Belfast", "Derry", "Lisburn", "Newry", "Bangor"],

  NSW: ["Sydney", "Newcastle", "Wollongong", "Central Coast", "Coffs Harbour"],
  VIC: ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"],
  QLD: ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns"],
  WA: ["Perth", "Fremantle", "Bunbury", "Joondalup", "Mandurah"],
  SA_AU: ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge"],
  TAS: ["Hobart", "Launceston", "Devonport", "Burnie"],
  ACT: ["Canberra", "Belconnen", "Tuggeranong"],
  NT_AU: ["Darwin", "Alice Springs", "Palmerston", "Katherine"],

  BW: ["Stuttgart", "Karlsruhe", "Freiburg", "Heidelberg", "Mannheim"],
  BY: ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Würzburg"],
  BE_DE: ["Berlin"],
  BB: ["Potsdam", "Cottbus", "Brandenburg an der Havel"],
  HB: ["Bremen", "Bremerhaven"],
  HH: ["Hamburg"],
  HE: ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"],
  MV: ["Rostock", "Schwerin", "Neubrandenburg"],
  NI: ["Hanover", "Braunschweig", "Oldenburg", "Osnabrück", "Göttingen"],
  NW: ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Bonn", "Münster"],
  RP: ["Mainz", "Ludwigshafen", "Koblenz", "Trier"],
  SL: ["Saarbrücken"],
  SN: ["Dresden", "Leipzig", "Chemnitz"],
  ST: ["Magdeburg", "Halle"],
  SH: ["Kiel", "Lübeck", "Flensburg"],
  TH: ["Erfurt", "Jena", "Weimar"],

  IDF: ["Paris", "Versailles", "Boulogne-Billancourt", "Saint-Denis", "Nanterre"],
  ARA: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand"],
  HDF: ["Lille", "Amiens", "Roubaix", "Dunkirk"],
  NAQ: ["Bordeaux", "Limoges", "Poitiers", "La Rochelle"],
  OCC: ["Toulouse", "Montpellier", "Nîmes", "Perpignan"],
  PAC: ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Cannes"],
  GES: ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"],
  BRE: ["Rennes", "Brest", "Quimper", "Saint-Malo"],
  NOR: ["Rouen", "Le Havre", "Caen"],
  PDL: ["Nantes", "Angers", "Le Mans"],
  CVL: ["Tours", "Orléans", "Blois"],
  BFC: ["Dijon", "Besançon"],
  COR: ["Ajaccio", "Bastia"],

  MH: ["Mumbai", "Pune", "Nagpur", "Thane", "Navi Mumbai", "Nashik"],
  DL: ["New Delhi", "Noida", "Gurgaon", "Faridabad", "Ghaziabad"],
  KA: ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum"],
  TN: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
  UP: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad", "Meerut"],
  GJ: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"],
  WB: ["Kolkata", "Howrah", "Asansol", "Siliguri", "Durgapur"],
  RJ: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Udaipur", "Ajmer"],
  TS: ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"],
  AP: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati"],
  KL: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur"],
  PB: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala"],
  HR: ["Gurgaon", "Faridabad", "Panipat", "Ambala", "Karnal"],
  MP: ["Bhopal", "Indore", "Jabalpur", "Gwalior"],
  BR_IN: ["Patna", "Gaya", "Muzaffarpur"],
  OD: ["Bhubaneswar", "Cuttack", "Rourkela"],
  CG: ["Raipur", "Bhilai", "Bilaspur"],
  JH: ["Ranchi", "Jamshedpur", "Dhanbad"],

  JP13: ["Tokyo", "Shibuya", "Shinjuku", "Minato", "Chiyoda"],
  JP27: ["Osaka", "Sakai", "Higashiosaka"],
  JP23: ["Nagoya", "Toyota", "Okazaki"],
  JP14: ["Yokohama", "Kawasaki", "Sagamihara"],
  JP11: ["Saitama", "Kawagoe", "Kawaguchi"],
  JP12: ["Chiba", "Funabashi", "Kashiwa"],
  JP01: ["Sapporo", "Asahikawa", "Hakodate"],
  JP40: ["Fukuoka", "Kitakyushu"],
  JP26: ["Kyoto"],
  JP28: ["Kobe", "Himeji", "Nishinomiya"],

  AGU: ["Aguascalientes"],
  BCN: ["Tijuana", "Mexicali", "Ensenada"],
  CMX: ["Mexico City"],
  JAL: ["Guadalajara", "Zapopan", "Tlaquepaque"],
  NLE: ["Monterrey", "San Pedro Garza García", "San Nicolás"],
  GUA: ["León", "Irapuato", "Celaya"],
  PUE: ["Puebla", "Tehuacán"],
  QUE: ["Querétaro"],
  YUC: ["Mérida"],

  SP: ["São Paulo", "Campinas", "Santos", "Guarulhos", "Ribeirão Preto"],
  RJ_BR: ["Rio de Janeiro", "Niterói", "Petrópolis"],
  MG: ["Belo Horizonte", "Uberlândia", "Juiz de Fora"],
  BA: ["Salvador", "Feira de Santana"],
  RS: ["Porto Alegre", "Caxias do Sul", "Pelotas"],
  PR: ["Curitiba", "Londrina", "Maringá"],
  PE_BR: ["Recife", "Olinda", "Jaboatão"],
  CE: ["Fortaleza", "Juazeiro do Norte"],
  DF: ["Brasília"],
  SC: ["Florianópolis", "Joinville", "Blumenau"],
  GO: ["Goiânia", "Aparecida de Goiânia"],

  LAZ: ["Rome", "Latina", "Frosinone"],
  LOM: ["Milan", "Bergamo", "Brescia", "Monza"],
  CAM: ["Naples", "Salerno", "Caserta"],
  SIC: ["Palermo", "Catania", "Messina"],
  VEN: ["Venice", "Verona", "Padua", "Vicenza"],
  PIE: ["Turin", "Novara", "Alessandria"],
  EMR: ["Bologna", "Modena", "Parma", "Rimini"],
  TOS: ["Florence", "Pisa", "Livorno", "Siena"],

  MD: ["Madrid", "Alcalá de Henares", "Getafe"],
  CT: ["Barcelona", "Tarragona", "Girona"],
  AN: ["Seville", "Málaga", "Granada", "Córdoba"],
  VC: ["Valencia", "Alicante", "Castellón"],

  NH: ["Amsterdam", "Haarlem", "Hilversum"],
  ZH: ["Rotterdam", "The Hague", "Leiden", "Delft"],
  NB_NL: ["Eindhoven", "Tilburg", "Breda"],
  GE: ["Arnhem", "Nijmegen", "Apeldoorn"],
  UT: ["Utrecht", "Amersfoort"],

  ZH_CH: ["Zürich", "Winterthur"],
  BE_CH: ["Bern", "Thun", "Biel"],
  VD: ["Lausanne", "Montreux", "Nyon"],
  GE_CH: ["Geneva"],
  LU_CH: ["Lucerne"],
  BS: ["Basel"],
  TI: ["Lugano", "Bellinzona"],

  AUH: ["Abu Dhabi", "Al Ain"],
  DXB: ["Dubai", "Jebel Ali"],
  SHJ: ["Sharjah"],
  RAK: ["Ras al-Khaimah"],

  GP: ["Johannesburg", "Pretoria", "Soweto", "Sandton"],
  WC: ["Cape Town", "Stellenbosch", "Paarl"],
  KZN: ["Durban", "Pietermaritzburg", "Richards Bay"],
  EC: ["Port Elizabeth", "East London"],

  SEL: ["Seoul"],
  PUS: ["Busan"],
  ICN: ["Incheon"],
  GGD: ["Suwon", "Seongnam", "Goyang", "Yongin"],

  BJ: ["Beijing"],
  SH_CN: ["Shanghai"],
  GD: ["Guangzhou", "Shenzhen", "Dongguan", "Foshan", "Zhuhai"],
  ZJ: ["Hangzhou", "Ningbo", "Wenzhou"],
  JS: ["Nanjing", "Suzhou", "Wuxi"],

  LA: ["Lagos", "Ikeja", "Lekki"],
  ABJ: ["Abuja"],
  KN: ["Kano"],
  RV: ["Port Harcourt"],

  NCR: ["Manila", "Quezon City", "Makati", "Taguig", "Pasig"],
  CEB: ["Cebu City", "Mandaue", "Lapu-Lapu"],
  DVO: ["Davao City"],

  IST: ["Istanbul"],
  ANK: ["Ankara"],
  IZM: ["Izmir"],
  ANT: ["Antalya"],

  MZ: ["Warsaw"],
  ML_PL: ["Kraków"],
  WP: ["Poznań"],
  DS: ["Wrocław"],

  BOG: ["Bogotá"],
  ANT_CO: ["Medellín"],
  VAL: ["Cali"],

  CABA: ["Buenos Aires"],
  BA_AR: ["La Plata", "Mar del Plata"],
  COR_AR: ["Córdoba"],
  SFE: ["Rosario", "Santa Fe"],

  AKL: ["Auckland"],
  WGN: ["Wellington"],
  CAN: ["Christchurch"],
  WKO: ["Hamilton"],
  OTA: ["Dunedin", "Queenstown"],

  RYD: ["Riyadh"],
  MKH: ["Mecca", "Jeddah"],
  ESH: ["Dammam", "Dhahran", "Al Khobar"],

  TA: ["Tel Aviv", "Ramat Gan", "Bnei Brak"],
  JM: ["Jerusalem"],
  HFA: ["Haifa"],

  STK: ["Stockholm"],
  VGT: ["Gothenburg"],
  SKN: ["Malmö"],

  OSL: ["Oslo"],
  VKN: ["Bergen"],

  CPH: ["Copenhagen"],
  SDK: ["Odense"],

  DUB: ["Dublin"],
  CRK: ["Cork"],
  GAL: ["Galway"],

  SG_C: ["Singapore Central"],
  SG_N: ["Woodlands", "Yishun"],
  SG_E: ["Tampines", "Bedok"],
  SG_W: ["Jurong", "Clementi"],
  SG_NE: ["Sengkang", "Punggol"],

  HKI: ["Central", "Wan Chai", "Causeway Bay"],
  KLN: ["Tsim Sha Tsui", "Mong Kok", "Kowloon Bay"],
  NTR: ["Sha Tin", "Tsuen Wan", "Tuen Mun"],
};

const cache: { countries?: LocationOption[]; states?: Record<string, LocationOption[]>; cities?: Record<string, string[]> } = {};

export function getCountries(): LocationOption[] {
  if (cache.countries) return cache.countries;
  cache.countries = COUNTRIES;
  return cache.countries;
}

export function getStates(countryCode: string): LocationOption[] {
  if (!cache.states) cache.states = STATES_BY_COUNTRY;
  return cache.states[countryCode] ?? [];
}

export function getCities(stateCode: string): string[] {
  if (!cache.cities) cache.cities = CITIES_BY_STATE;
  return cache.cities[stateCode] ?? [];
}
