kind = "api"
  previewPath = "/api"
  title = "API Server"
  version = "1.0.0"
  id = "3B4_FFSkEVBkAeYMFRJ2e"

  [[services]]
  localPort = 3001
  name = "API Server"
  paths = ["/api"]

  [services.development]
  run = "PORT=3001 pnpm run dev:server"

  [services.env]
  PORT = "3001"

  [services.production]
  build = "pnpm run build"

  [services.production.run]
  args = ["pnpm", "run", "start"]

  [services.production.run.env]
  PORT = "3000"

  [services.production.health.startup]
  path = "/api/healthz"
  