// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trading-chart/MarketsChart.tsx": () => import("../components/mockups/trading-chart/MarketsChart.tsx"),
  "./components/mockups/trading-chart/OverviewChart.tsx": () => import("../components/mockups/trading-chart/OverviewChart.tsx")
};
