export interface LocationOption {
  code: string;
  label: string;
}

const COUNTRIES: LocationOption[] = [
  { code: "AF", label: "Afghanistan" },
  { code: "AL", label: "Albania" },
  { code: "DZ", label: "Algeria" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AG", label: "Antigua and Barbuda" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaijan" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Bahrain" },
  { code: "BD", label: "Bangladesh" },
  { code: "BB", label: "Barbados" },
  { code: "BY", label: "Belarus" },
  { code: "BE", label: "Belgium" },
  { code: "BZ", label: "Belize" },
  { code: "BJ", label: "Benin" },
  { code: "BT", label: "Bhutan" },
  { code: "BO", label: "Bolivia" },
  { code: "BA", label: "Bosnia and Herzegovina" },
  { code: "BW", label: "Botswana" },
  { code: "BR", label: "Brazil" },
  { code: "BN", label: "Brunei" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KH", label: "Cambodia" },
  { code: "CM", label: "Cameroon" },
  { code: "CA", label: "Canada" },
  { code: "CF", label: "Central African Republic" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoros" },
  { code: "CG", label: "Congo" },
  { code: "CD", label: "Congo (DRC)" },
  { code: "CR", label: "Costa Rica" },
  { code: "CI", label: "Côte d'Ivoire" },
  { code: "HR", label: "Croatia" },
  { code: "CU", label: "Cuba" },
  { code: "CY", label: "Cyprus" },
  { code: "CZ", label: "Czech Republic" },
  { code: "DK", label: "Denmark" },
  { code: "DJ", label: "Djibouti" },
  { code: "DM", label: "Dominica" },
  { code: "DO", label: "Dominican Republic" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egypt" },
  { code: "SV", label: "El Salvador" },
  { code: "GQ", label: "Equatorial Guinea" },
  { code: "ER", label: "Eritrea" },
  { code: "EE", label: "Estonia" },
  { code: "SZ", label: "Eswatini" },
  { code: "ET", label: "Ethiopia" },
  { code: "FJ", label: "Fiji" },
  { code: "FI", label: "Finland" },
  { code: "FR", label: "France" },
  { code: "GA", label: "Gabon" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "DE", label: "Germany" },
  { code: "GH", label: "Ghana" },
  { code: "GR", label: "Greece" },
  { code: "GD", label: "Grenada" },
  { code: "GT", label: "Guatemala" },
  { code: "GN", label: "Guinea" },
  { code: "GW", label: "Guinea-Bissau" },
  { code: "GY", label: "Guyana" },
  { code: "HT", label: "Haiti" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hungary" },
  { code: "IS", label: "Iceland" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IR", label: "Iran" },
  { code: "IQ", label: "Iraq" },
  { code: "IE", label: "Ireland" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italy" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japan" },
  { code: "JO", label: "Jordan" },
  { code: "KZ", label: "Kazakhstan" },
  { code: "KE", label: "Kenya" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "KG", label: "Kyrgyzstan" },
  { code: "LA", label: "Laos" },
  { code: "LV", label: "Latvia" },
  { code: "LB", label: "Lebanon" },
  { code: "LS", label: "Lesotho" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libya" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lithuania" },
  { code: "LU", label: "Luxembourg" },
  { code: "MO", label: "Macau" },
  { code: "MG", label: "Madagascar" },
  { code: "MW", label: "Malawi" },
  { code: "MY", label: "Malaysia" },
  { code: "MV", label: "Maldives" },
  { code: "ML", label: "Mali" },
  { code: "MT", label: "Malta" },
  { code: "MH", label: "Marshall Islands" },
  { code: "MR", label: "Mauritania" },
  { code: "MU", label: "Mauritius" },
  { code: "MX", label: "Mexico" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldova" },
  { code: "MC", label: "Monaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MA", label: "Morocco" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NL", label: "Netherlands" },
  { code: "NZ", label: "New Zealand" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Niger" },
  { code: "NG", label: "Nigeria" },
  { code: "KP", label: "North Korea" },
  { code: "MK", label: "North Macedonia" },
  { code: "NO", label: "Norway" },
  { code: "OM", label: "Oman" },
  { code: "PK", label: "Pakistan" },
  { code: "PW", label: "Palau" },
  { code: "PS", label: "Palestine" },
  { code: "PA", label: "Panama" },
  { code: "PG", label: "Papua New Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Peru" },
  { code: "PH", label: "Philippines" },
  { code: "PL", label: "Poland" },
  { code: "PT", label: "Portugal" },
  { code: "PR", label: "Puerto Rico" },
  { code: "QA", label: "Qatar" },
  { code: "RO", label: "Romania" },
  { code: "RU", label: "Russia" },
  { code: "RW", label: "Rwanda" },
  { code: "KN", label: "Saint Kitts and Nevis" },
  { code: "LC", label: "Saint Lucia" },
  { code: "VC", label: "Saint Vincent and the Grenadines" },
  { code: "WS", label: "Samoa" },
  { code: "SM", label: "San Marino" },
  { code: "ST", label: "São Tomé and Príncipe" },
  { code: "SA", label: "Saudi Arabia" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leone" },
  { code: "SG", label: "Singapore" },
  { code: "SK", label: "Slovakia" },
  { code: "SI", label: "Slovenia" },
  { code: "SB", label: "Solomon Islands" },
  { code: "SO", label: "Somalia" },
  { code: "ZA", label: "South Africa" },
  { code: "KR", label: "South Korea" },
  { code: "SS", label: "South Sudan" },
  { code: "ES", label: "Spain" },
  { code: "LK", label: "Sri Lanka" },
  { code: "SD", label: "Sudan" },
  { code: "SR", label: "Suriname" },
  { code: "SE", label: "Sweden" },
  { code: "CH", label: "Switzerland" },
  { code: "SY", label: "Syria" },
  { code: "TW", label: "Taiwan" },
  { code: "TJ", label: "Tajikistan" },
  { code: "TZ", label: "Tanzania" },
  { code: "TH", label: "Thailand" },
  { code: "TL", label: "Timor-Leste" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad and Tobago" },
  { code: "TN", label: "Tunisia" },
  { code: "TR", label: "Turkey" },
  { code: "TM", label: "Turkmenistan" },
  { code: "TV", label: "Tuvalu" },
  { code: "UG", label: "Uganda" },
  { code: "UA", label: "Ukraine" },
  { code: "AE", label: "United Arab Emirates" },
  { code: "GB", label: "United Kingdom" },
  { code: "US", label: "United States" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistan" },
  { code: "VU", label: "Vanuatu" },
  { code: "VA", label: "Vatican City" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yemen" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabwe" },
];

function alpha(arr: LocationOption[]): LocationOption[] {
  return [...arr].sort((a, b) => a.label.localeCompare(b.label));
}

function alphaStrings(arr: string[]): string[] {
  return [...arr].sort((a, b) => a.localeCompare(b));
}

const US_STATES: LocationOption[] = alpha([
  "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware",
  "District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa",
  "Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota",
  "Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey",
  "New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
  "Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah",
  "Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming",
].map((s) => ({ code: s, label: s })));

const STATES_BY_COUNTRY: Record<string, LocationOption[]> = {
  US: US_STATES,

  CA: alpha([
    { code: "AB", label: "Alberta" },
    { code: "BC", label: "British Columbia" },
    { code: "MB", label: "Manitoba" },
    { code: "NB", label: "New Brunswick" },
    { code: "NL_CA", label: "Newfoundland and Labrador" },
    { code: "NS", label: "Nova Scotia" },
    { code: "NT", label: "Northwest Territories" },
    { code: "NU", label: "Nunavut" },
    { code: "ON", label: "Ontario" },
    { code: "PE", label: "Prince Edward Island" },
    { code: "QC", label: "Quebec" },
    { code: "SK", label: "Saskatchewan" },
    { code: "YT", label: "Yukon" },
  ]),

  GB: alpha([
    { code: "ENG", label: "England" },
    { code: "NIR", label: "Northern Ireland" },
    { code: "SCT", label: "Scotland" },
    { code: "WLS", label: "Wales" },
  ]),

  AU: alpha([
    { code: "ACT", label: "Australian Capital Territory" },
    { code: "NSW", label: "New South Wales" },
    { code: "NT_AU", label: "Northern Territory" },
    { code: "QLD", label: "Queensland" },
    { code: "SA_AU", label: "South Australia" },
    { code: "TAS", label: "Tasmania" },
    { code: "VIC", label: "Victoria" },
    { code: "WA", label: "Western Australia" },
  ]),

  DE: alpha([
    { code: "BW", label: "Baden-Württemberg" },
    { code: "BY", label: "Bavaria" },
    { code: "BE_DE", label: "Berlin" },
    { code: "BB", label: "Brandenburg" },
    { code: "HB", label: "Bremen" },
    { code: "HH", label: "Hamburg" },
    { code: "HE", label: "Hesse" },
    { code: "NI_DE", label: "Lower Saxony" },
    { code: "MV", label: "Mecklenburg-Vorpommern" },
    { code: "NW", label: "North Rhine-Westphalia" },
    { code: "RP", label: "Rhineland-Palatinate" },
    { code: "SL_DE", label: "Saarland" },
    { code: "SN_DE", label: "Saxony" },
    { code: "ST_DE", label: "Saxony-Anhalt" },
    { code: "SH", label: "Schleswig-Holstein" },
    { code: "TH_DE", label: "Thuringia" },
  ]),

  FR: alpha([
    { code: "ARA", label: "Auvergne-Rhône-Alpes" },
    { code: "BFC", label: "Bourgogne-Franche-Comté" },
    { code: "BRE", label: "Brittany" },
    { code: "CVL", label: "Centre-Val de Loire" },
    { code: "COR", label: "Corsica" },
    { code: "GES", label: "Grand Est" },
    { code: "HDF", label: "Hauts-de-France" },
    { code: "IDF", label: "Île-de-France" },
    { code: "NOR", label: "Normandy" },
    { code: "NAQ", label: "Nouvelle-Aquitaine" },
    { code: "OCC", label: "Occitanie" },
    { code: "PDL", label: "Pays de la Loire" },
    { code: "PAC", label: "Provence-Alpes-Côte d'Azur" },
  ]),

  IN: alpha([
    { code: "AP", label: "Andhra Pradesh" },
    { code: "AR_IN", label: "Arunachal Pradesh" },
    { code: "AS", label: "Assam" },
    { code: "BR_IN", label: "Bihar" },
    { code: "CG_IN", label: "Chhattisgarh" },
    { code: "DL", label: "Delhi" },
    { code: "GA_IN", label: "Goa" },
    { code: "GJ", label: "Gujarat" },
    { code: "HR_IN", label: "Haryana" },
    { code: "HP", label: "Himachal Pradesh" },
    { code: "JH", label: "Jharkhand" },
    { code: "KA", label: "Karnataka" },
    { code: "KL", label: "Kerala" },
    { code: "MP_IN", label: "Madhya Pradesh" },
    { code: "MH", label: "Maharashtra" },
    { code: "MN_IN", label: "Manipur" },
    { code: "ML_IN", label: "Meghalaya" },
    { code: "MZ_IN", label: "Mizoram" },
    { code: "NL_IN", label: "Nagaland" },
    { code: "OD", label: "Odisha" },
    { code: "PB", label: "Punjab" },
    { code: "RJ", label: "Rajasthan" },
    { code: "SK_IN", label: "Sikkim" },
    { code: "TN", label: "Tamil Nadu" },
    { code: "TS", label: "Telangana" },
    { code: "TR_IN", label: "Tripura" },
    { code: "UP", label: "Uttar Pradesh" },
    { code: "UK_IN", label: "Uttarakhand" },
    { code: "WB", label: "West Bengal" },
  ]),

  JP: alpha([
    { code: "JP23", label: "Aichi" },
    { code: "JP12", label: "Chiba" },
    { code: "JP40", label: "Fukuoka" },
    { code: "JP01", label: "Hokkaido" },
    { code: "JP28", label: "Hyogo" },
    { code: "JP14", label: "Kanagawa" },
    { code: "JP26", label: "Kyoto" },
    { code: "JP27", label: "Osaka" },
    { code: "JP11", label: "Saitama" },
    { code: "JP13", label: "Tokyo" },
  ]),

  MX: alpha([
    { code: "AGU", label: "Aguascalientes" },
    { code: "BCN", label: "Baja California" },
    { code: "BCS", label: "Baja California Sur" },
    { code: "CAM_MX", label: "Campeche" },
    { code: "CHP", label: "Chiapas" },
    { code: "CHH", label: "Chihuahua" },
    { code: "CMX", label: "Ciudad de México" },
    { code: "COA", label: "Coahuila" },
    { code: "COL_MX", label: "Colima" },
    { code: "DUR", label: "Durango" },
    { code: "MEX", label: "Estado de México" },
    { code: "GUA", label: "Guanajuato" },
    { code: "GRO", label: "Guerrero" },
    { code: "HID", label: "Hidalgo" },
    { code: "JAL", label: "Jalisco" },
    { code: "MIC", label: "Michoacán" },
    { code: "MOR", label: "Morelos" },
    { code: "NAY", label: "Nayarit" },
    { code: "NLE", label: "Nuevo León" },
    { code: "OAX", label: "Oaxaca" },
    { code: "PUE", label: "Puebla" },
    { code: "QUE", label: "Querétaro" },
    { code: "ROO", label: "Quintana Roo" },
    { code: "SLP", label: "San Luis Potosí" },
    { code: "SIN", label: "Sinaloa" },
    { code: "SON", label: "Sonora" },
    { code: "TAB", label: "Tabasco" },
    { code: "TAM", label: "Tamaulipas" },
    { code: "TLA", label: "Tlaxcala" },
    { code: "VER", label: "Veracruz" },
    { code: "YUC", label: "Yucatán" },
    { code: "ZAC", label: "Zacatecas" },
  ]),

  BR: alpha([
    { code: "AC", label: "Acre" },
    { code: "AL_BR", label: "Alagoas" },
    { code: "AP_BR", label: "Amapá" },
    { code: "AM", label: "Amazonas" },
    { code: "BA", label: "Bahia" },
    { code: "CE", label: "Ceará" },
    { code: "DF_BR", label: "Distrito Federal" },
    { code: "ES_BR", label: "Espírito Santo" },
    { code: "GO", label: "Goiás" },
    { code: "MA_BR", label: "Maranhão" },
    { code: "MT", label: "Mato Grosso" },
    { code: "MS", label: "Mato Grosso do Sul" },
    { code: "MG_BR", label: "Minas Gerais" },
    { code: "PA_BR", label: "Pará" },
    { code: "PB_BR", label: "Paraíba" },
    { code: "PR_BR", label: "Paraná" },
    { code: "PE_BR", label: "Pernambuco" },
    { code: "PI", label: "Piauí" },
    { code: "RJ_BR", label: "Rio de Janeiro" },
    { code: "RN", label: "Rio Grande do Norte" },
    { code: "RS", label: "Rio Grande do Sul" },
    { code: "RO_BR", label: "Rondônia" },
    { code: "RR", label: "Roraima" },
    { code: "SC_BR", label: "Santa Catarina" },
    { code: "SP", label: "São Paulo" },
    { code: "SE_BR", label: "Sergipe" },
    { code: "TO_BR", label: "Tocantins" },
  ]),

  IT: alpha([
    { code: "ABR", label: "Abruzzo" },
    { code: "BAS", label: "Basilicata" },
    { code: "CAL", label: "Calabria" },
    { code: "CAM_IT", label: "Campania" },
    { code: "EMR", label: "Emilia-Romagna" },
    { code: "FVG", label: "Friuli Venezia Giulia" },
    { code: "LAZ", label: "Lazio" },
    { code: "LIG", label: "Liguria" },
    { code: "LOM", label: "Lombardy" },
    { code: "MAR", label: "Marche" },
    { code: "MOL", label: "Molise" },
    { code: "PIE", label: "Piedmont" },
    { code: "PUG", label: "Puglia" },
    { code: "SAR", label: "Sardinia" },
    { code: "SIC", label: "Sicily" },
    { code: "TOS", label: "Tuscany" },
    { code: "TAA", label: "Trentino-Alto Adige" },
    { code: "UMB", label: "Umbria" },
    { code: "VDA", label: "Valle d'Aosta" },
    { code: "VEN", label: "Veneto" },
  ]),

  ES: alpha([
    { code: "AN_ES", label: "Andalusia" },
    { code: "AR_ES", label: "Aragon" },
    { code: "AS_ES", label: "Asturias" },
    { code: "IB", label: "Balearic Islands" },
    { code: "PV", label: "Basque Country" },
    { code: "CN_ES", label: "Canary Islands" },
    { code: "CB", label: "Cantabria" },
    { code: "CM_ES", label: "Castilla-La Mancha" },
    { code: "CL_ES", label: "Castile and León" },
    { code: "CT", label: "Catalonia" },
    { code: "EX", label: "Extremadura" },
    { code: "GA_ES", label: "Galicia" },
    { code: "RI", label: "La Rioja" },
    { code: "MD_ES", label: "Madrid" },
    { code: "MU", label: "Murcia" },
    { code: "NA_ES", label: "Navarre" },
    { code: "VC_ES", label: "Valencia" },
  ]),

  NL: alpha([
    { code: "DR", label: "Drenthe" },
    { code: "FL", label: "Flevoland" },
    { code: "FR_NL", label: "Friesland" },
    { code: "GE_NL", label: "Gelderland" },
    { code: "GR_NL", label: "Groningen" },
    { code: "LI_NL", label: "Limburg" },
    { code: "NB_NL", label: "North Brabant" },
    { code: "NH", label: "North Holland" },
    { code: "OV", label: "Overijssel" },
    { code: "ZH_NL", label: "South Holland" },
    { code: "UT_NL", label: "Utrecht" },
    { code: "ZE", label: "Zeeland" },
  ]),

  CH: alpha([
    { code: "AG", label: "Aargau" },
    { code: "AI", label: "Appenzell Innerrhoden" },
    { code: "AR_CH", label: "Appenzell Ausserrhoden" },
    { code: "BS_CH", label: "Basel-Stadt" },
    { code: "BL", label: "Basel-Landschaft" },
    { code: "BE_CH", label: "Bern" },
    { code: "FR_CH", label: "Fribourg" },
    { code: "GE_CH", label: "Geneva" },
    { code: "GL", label: "Glarus" },
    { code: "GR_CH", label: "Graubünden" },
    { code: "JU", label: "Jura" },
    { code: "LU_CH", label: "Lucerne" },
    { code: "NE_CH", label: "Neuchâtel" },
    { code: "NW_CH", label: "Nidwalden" },
    { code: "OW", label: "Obwalden" },
    { code: "SG", label: "St. Gallen" },
    { code: "SH_CH", label: "Schaffhausen" },
    { code: "SZ", label: "Schwyz" },
    { code: "SO", label: "Solothurn" },
    { code: "TG", label: "Thurgau" },
    { code: "TI", label: "Ticino" },
    { code: "UR", label: "Uri" },
    { code: "VS", label: "Valais" },
    { code: "VD", label: "Vaud" },
    { code: "ZG", label: "Zug" },
    { code: "ZH_CH", label: "Zürich" },
  ]),

  AE: alpha([
    { code: "AUH", label: "Abu Dhabi" },
    { code: "AJM", label: "Ajman" },
    { code: "DXB", label: "Dubai" },
    { code: "FUJ", label: "Fujairah" },
    { code: "RAK", label: "Ras al-Khaimah" },
    { code: "SHJ", label: "Sharjah" },
    { code: "UAQ", label: "Umm al-Quwain" },
  ]),

  ZA: alpha([
    { code: "EC_ZA", label: "Eastern Cape" },
    { code: "FS", label: "Free State" },
    { code: "GP", label: "Gauteng" },
    { code: "KZN", label: "KwaZulu-Natal" },
    { code: "LP", label: "Limpopo" },
    { code: "MP_ZA", label: "Mpumalanga" },
    { code: "NC_ZA", label: "Northern Cape" },
    { code: "NW_ZA", label: "North West" },
    { code: "WC", label: "Western Cape" },
  ]),

  KR: alpha([
    { code: "PUS", label: "Busan" },
    { code: "DGU", label: "Daegu" },
    { code: "DJN", label: "Daejeon" },
    { code: "GGD", label: "Gyeonggi-do" },
    { code: "GWJ", label: "Gwangju" },
    { code: "ICN", label: "Incheon" },
    { code: "SEL", label: "Seoul" },
  ]),

  CN: alpha([
    { code: "BJ_CN", label: "Beijing" },
    { code: "CQ", label: "Chongqing" },
    { code: "FJ_CN", label: "Fujian" },
    { code: "GD_CN", label: "Guangdong" },
    { code: "GX", label: "Guangxi" },
    { code: "GZ_CN", label: "Guizhou" },
    { code: "HI_CN", label: "Hainan" },
    { code: "HEB", label: "Hebei" },
    { code: "HLJ", label: "Heilongjiang" },
    { code: "HEN", label: "Henan" },
    { code: "HUB", label: "Hubei" },
    { code: "HN_CN", label: "Hunan" },
    { code: "NMG", label: "Inner Mongolia" },
    { code: "JS_CN", label: "Jiangsu" },
    { code: "JX", label: "Jiangxi" },
    { code: "JL", label: "Jilin" },
    { code: "LN", label: "Liaoning" },
    { code: "NX", label: "Ningxia" },
    { code: "QH", label: "Qinghai" },
    { code: "SN_CN", label: "Shaanxi" },
    { code: "SD_CN", label: "Shandong" },
    { code: "SH_CN", label: "Shanghai" },
    { code: "SX", label: "Shanxi" },
    { code: "SC_CN", label: "Sichuan" },
    { code: "TJ_CN", label: "Tianjin" },
    { code: "XZ", label: "Tibet" },
    { code: "XJ", label: "Xinjiang" },
    { code: "YN", label: "Yunnan" },
    { code: "ZJ_CN", label: "Zhejiang" },
  ]),

  NG: alpha([
    { code: "ABJ", label: "Abuja (FCT)" },
    { code: "KN_NG", label: "Kano" },
    { code: "LA_NG", label: "Lagos" },
    { code: "OG", label: "Ogun" },
    { code: "OY", label: "Oyo" },
    { code: "RV", label: "Rivers" },
  ]),

  PH: alpha([
    { code: "BUL", label: "Bulacan" },
    { code: "CAV", label: "Cavite" },
    { code: "CEB", label: "Cebu" },
    { code: "DVO", label: "Davao" },
    { code: "ILO_PH", label: "Iloilo" },
    { code: "LAG_PH", label: "Laguna" },
    { code: "NCR", label: "Metro Manila (NCR)" },
  ]),

  TR: alpha([
    { code: "ADN", label: "Adana" },
    { code: "ANK", label: "Ankara" },
    { code: "ANT_TR", label: "Antalya" },
    { code: "BRS_TR", label: "Bursa" },
    { code: "IST", label: "Istanbul" },
    { code: "IZM", label: "Izmir" },
  ]),

  PL: alpha([
    { code: "DS_PL", label: "Lower Silesia" },
    { code: "KP", label: "Kuyavia-Pomerania" },
    { code: "LD", label: "Łódź" },
    { code: "ML_PL", label: "Lesser Poland" },
    { code: "MZ_PL", label: "Masovia (Warsaw)" },
    { code: "PM_PL", label: "Pomerania" },
    { code: "SL_PL", label: "Silesia" },
    { code: "WP_PL", label: "Greater Poland" },
  ]),

  CO: alpha([
    { code: "ANT_CO", label: "Antioquia" },
    { code: "ATL_CO", label: "Atlántico" },
    { code: "BOG", label: "Bogotá D.C." },
    { code: "SAN_CO", label: "Santander" },
    { code: "VAL_CO", label: "Valle del Cauca" },
  ]),

  AR: alpha([
    { code: "CABA", label: "Buenos Aires (City)" },
    { code: "BA_AR", label: "Buenos Aires (Province)" },
    { code: "COR_AR", label: "Córdoba" },
    { code: "MZA", label: "Mendoza" },
    { code: "SFE", label: "Santa Fe" },
    { code: "TUC", label: "Tucumán" },
  ]),

  NZ: alpha([
    { code: "AKL", label: "Auckland" },
    { code: "BOP", label: "Bay of Plenty" },
    { code: "CAN_NZ", label: "Canterbury" },
    { code: "OTA", label: "Otago" },
    { code: "WKO", label: "Waikato" },
    { code: "WGN", label: "Wellington" },
  ]),

  SA: alpha([
    { code: "ASR", label: "Asir" },
    { code: "ESH_SA", label: "Eastern Province" },
    { code: "MDN", label: "Madinah" },
    { code: "MKH", label: "Makkah" },
    { code: "RYD", label: "Riyadh" },
  ]),

  IL: alpha([
    { code: "CTR_IL", label: "Central District" },
    { code: "HFA", label: "Haifa District" },
    { code: "JM_IL", label: "Jerusalem District" },
    { code: "NTH_IL", label: "Northern District" },
    { code: "STH_IL", label: "Southern District" },
    { code: "TA", label: "Tel Aviv District" },
  ]),

  SE: alpha([
    { code: "SKN", label: "Skåne" },
    { code: "STK", label: "Stockholm" },
    { code: "VGT", label: "Västra Götaland" },
  ]),

  NO: alpha([
    { code: "OSL", label: "Oslo" },
    { code: "TRO_NO", label: "Trøndelag" },
    { code: "VKN", label: "Vestland" },
  ]),

  DK: alpha([
    { code: "CPH", label: "Capital Region" },
    { code: "MDJ", label: "Central Jutland" },
    { code: "SDK", label: "Southern Denmark" },
  ]),

  IE: alpha([
    { code: "CRK", label: "Cork" },
    { code: "DUB", label: "Dublin" },
    { code: "GAL_IE", label: "Galway" },
    { code: "LMK", label: "Limerick" },
  ]),

  SG: alpha([
    { code: "SG_C", label: "Central Region" },
    { code: "SG_E", label: "East Region" },
    { code: "SG_N", label: "North Region" },
    { code: "SG_NE", label: "North-East Region" },
    { code: "SG_W", label: "West Region" },
  ]),

  HK: alpha([
    { code: "HKI", label: "Hong Kong Island" },
    { code: "KLN", label: "Kowloon" },
    { code: "NTR", label: "New Territories" },
  ]),

  RU: alpha([
    { code: "KDA", label: "Krasnodar Krai" },
    { code: "MOW", label: "Moscow" },
    { code: "MOS", label: "Moscow Oblast" },
    { code: "NVS", label: "Novosibirsk Oblast" },
    { code: "SPE", label: "Saint Petersburg" },
    { code: "SVE", label: "Sverdlovsk Oblast" },
    { code: "TAT", label: "Tatarstan" },
  ]),

  PK: alpha([
    { code: "BA_PK", label: "Balochistan" },
    { code: "ICT", label: "Islamabad Capital Territory" },
    { code: "KP_PK", label: "Khyber Pakhtunkhwa" },
    { code: "PB_PK", label: "Punjab" },
    { code: "SD_PK", label: "Sindh" },
  ]),

  BD: alpha([
    { code: "BAR", label: "Barisal" },
    { code: "CHT", label: "Chittagong" },
    { code: "DHK", label: "Dhaka" },
    { code: "KHU", label: "Khulna" },
    { code: "RAJ_BD", label: "Rajshahi" },
    { code: "SYL", label: "Sylhet" },
  ]),

  EG: alpha([
    { code: "ALX", label: "Alexandria" },
    { code: "CAI", label: "Cairo" },
    { code: "GZ_EG", label: "Giza" },
    { code: "LUX", label: "Luxor" },
  ]),

  KE: alpha([
    { code: "CST_KE", label: "Coast" },
    { code: "CEN_KE", label: "Central" },
    { code: "NRB", label: "Nairobi" },
    { code: "RVP", label: "Rift Valley" },
  ]),

  GH: alpha([
    { code: "ASH", label: "Ashanti" },
    { code: "GAR", label: "Greater Accra" },
  ]),

  QA: alpha([
    { code: "DOH", label: "Doha" },
    { code: "RYN", label: "Al Rayyan" },
  ]),

  KW: alpha([
    { code: "AHM", label: "Ahmadi" },
    { code: "KWT", label: "Kuwait City" },
  ]),

  AT: alpha([
    { code: "BGL", label: "Burgenland" },
    { code: "KTN", label: "Carinthia" },
    { code: "NOE", label: "Lower Austria" },
    { code: "SBG", label: "Salzburg" },
    { code: "STM", label: "Styria" },
    { code: "TIR", label: "Tyrol" },
    { code: "OOE", label: "Upper Austria" },
    { code: "VBG", label: "Vorarlberg" },
    { code: "WIE", label: "Vienna" },
  ]),

  PT: alpha([
    { code: "AZO", label: "Azores" },
    { code: "FAR_PT", label: "Faro" },
    { code: "LIS", label: "Lisbon" },
    { code: "MAD_PT", label: "Madeira" },
    { code: "PRT", label: "Porto" },
  ]),

  GR: alpha([
    { code: "ATT", label: "Attica" },
    { code: "CMC", label: "Central Macedonia" },
    { code: "CRE", label: "Crete" },
    { code: "THS", label: "Thessaly" },
  ]),

  RO: alpha([
    { code: "BUC", label: "Bucharest" },
    { code: "CLJ", label: "Cluj" },
    { code: "CON_RO", label: "Constanța" },
    { code: "TIM", label: "Timiș" },
  ]),

  HU: alpha([
    { code: "BUD", label: "Budapest" },
    { code: "PES", label: "Pest" },
  ]),

  CZ: alpha([
    { code: "JMK", label: "South Moravian" },
    { code: "PHA", label: "Prague" },
  ]),

  TH: alpha([
    { code: "BKK", label: "Bangkok" },
    { code: "CNX", label: "Chiang Mai" },
    { code: "PKT", label: "Phuket" },
  ]),

  MY: alpha([
    { code: "JHR", label: "Johor" },
    { code: "KUL", label: "Kuala Lumpur" },
    { code: "PNG", label: "Penang" },
    { code: "SBH", label: "Sabah" },
    { code: "SRW", label: "Sarawak" },
    { code: "SGR", label: "Selangor" },
  ]),

  ID: alpha([
    { code: "BA_ID", label: "Bali" },
    { code: "JB", label: "East Java" },
    { code: "JK", label: "Jakarta" },
    { code: "JT", label: "Central Java" },
    { code: "JI", label: "West Java" },
  ]),

  VN: alpha([
    { code: "DAN", label: "Da Nang" },
    { code: "HAN", label: "Hanoi" },
    { code: "HCM", label: "Ho Chi Minh City" },
  ]),

  UA: alpha([
    { code: "KBP", label: "Kyiv" },
    { code: "LWO", label: "Lviv" },
    { code: "ODS", label: "Odesa" },
  ]),

  PE: alpha([
    { code: "ARE_PE", label: "Arequipa" },
    { code: "CUS", label: "Cusco" },
    { code: "LIM", label: "Lima" },
  ]),

  CL: alpha([
    { code: "BIO", label: "Biobío" },
    { code: "RM", label: "Santiago Metropolitan" },
    { code: "VAP", label: "Valparaíso" },
  ]),

  CR: alpha([
    { code: "SJ_CR", label: "San José" },
  ]),

  PA: alpha([
    { code: "PAN", label: "Panamá" },
  ]),

  JM: alpha([
    { code: "KNG", label: "Kingston" },
    { code: "SAN_JM", label: "Saint Andrew" },
  ]),

  TT: alpha([
    { code: "POS", label: "Port of Spain" },
    { code: "SFD", label: "San Fernando" },
  ]),

  FI: alpha([
    { code: "HEL", label: "Helsinki-Uusimaa" },
    { code: "PIR", label: "Pirkanmaa" },
  ]),

  BE: alpha([
    { code: "BRU", label: "Brussels" },
    { code: "FLA", label: "Flanders" },
    { code: "WAL", label: "Wallonia" },
  ]),

  TW: alpha([
    { code: "KHH", label: "Kaohsiung" },
    { code: "TNN", label: "Tainan" },
    { code: "TPE", label: "Taipei" },
  ]),
};

const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: ["Birmingham", "Dothan", "Hoover", "Huntsville", "Mobile", "Montgomery", "Tuscaloosa"],
  Alaska: ["Anchorage", "Fairbanks", "Juneau", "Ketchikan", "Kodiak", "Sitka", "Wasilla"],
  Arizona: ["Chandler", "Gilbert", "Glendale", "Mesa", "Peoria", "Phoenix", "Scottsdale", "Surprise", "Tempe", "Tucson"],
  Arkansas: ["Conway", "Fayetteville", "Fort Smith", "Jonesboro", "Little Rock", "North Little Rock", "Rogers", "Springdale"],
  California: ["Anaheim", "Bakersfield", "Chula Vista", "Fontana", "Fremont", "Fresno", "Irvine", "Long Beach", "Los Angeles", "Modesto", "Oakland", "Oxnard", "Riverside", "Sacramento", "San Bernardino", "San Diego", "San Francisco", "San Jose", "Santa Ana", "Stockton"],
  Colorado: ["Arvada", "Aurora", "Boulder", "Colorado Springs", "Denver", "Fort Collins", "Lakewood", "Pueblo", "Thornton", "Westminster"],
  Connecticut: ["Bridgeport", "Danbury", "Greenwich", "Hartford", "New Britain", "New Haven", "Norwalk", "Stamford", "Waterbury"],
  Delaware: ["Dover", "Georgetown", "Middletown", "Milford", "Newark", "Seaford", "Smyrna", "Wilmington"],
  "District of Columbia": ["Washington"],
  Florida: ["Cape Coral", "Coral Springs", "Davie", "Fort Lauderdale", "Gainesville", "Hialeah", "Hollywood", "Jacksonville", "Lakeland", "Miami", "Miami Gardens", "Miramar", "Orlando", "Pembroke Pines", "Pompano Beach", "Port St. Lucie", "St. Petersburg", "Tallahassee", "Tampa", "West Palm Beach"],
  Georgia: ["Albany", "Athens", "Atlanta", "Augusta", "Columbus", "Johns Creek", "Macon", "Roswell", "Sandy Springs", "Savannah"],
  Hawaii: ["Hilo", "Honolulu", "Kahului", "Kailua", "Kaneohe", "Mililani Town", "Pearl City", "Waipahu"],
  Idaho: ["Boise", "Caldwell", "Coeur d'Alene", "Idaho Falls", "Meridian", "Nampa", "Pocatello", "Twin Falls"],
  Illinois: ["Aurora", "Champaign", "Chicago", "Elgin", "Joliet", "Naperville", "Peoria", "Rockford", "Springfield", "Waukegan"],
  Indiana: ["Bloomington", "Carmel", "Evansville", "Fishers", "Fort Wayne", "Gary", "Hammond", "Indianapolis", "Lafayette", "South Bend"],
  Iowa: ["Ames", "Cedar Rapids", "Council Bluffs", "Davenport", "Des Moines", "Iowa City", "Sioux City", "Waterloo"],
  Kansas: ["Kansas City", "Lawrence", "Manhattan", "Olathe", "Overland Park", "Shawnee", "Topeka", "Wichita"],
  Kentucky: ["Bowling Green", "Covington", "Florence", "Hopkinsville", "Lexington", "Louisville", "Owensboro", "Richmond"],
  Louisiana: ["Baton Rouge", "Bossier City", "Kenner", "Lafayette", "Lake Charles", "Metairie", "Monroe", "New Orleans", "Shreveport"],
  Maine: ["Auburn", "Augusta", "Bangor", "Biddeford", "Lewiston", "Portland", "Sanford", "South Portland"],
  Maryland: ["Annapolis", "Baltimore", "Bowie", "College Park", "Frederick", "Gaithersburg", "Hagerstown", "Rockville", "Salisbury"],
  Massachusetts: ["Boston", "Brockton", "Cambridge", "Fall River", "Lowell", "Lynn", "New Bedford", "Quincy", "Springfield", "Worcester"],
  Michigan: ["Ann Arbor", "Clinton Township", "Dearborn", "Detroit", "Flint", "Grand Rapids", "Lansing", "Livonia", "Sterling Heights", "Warren"],
  Minnesota: ["Bloomington", "Brooklyn Park", "Duluth", "Minneapolis", "Plymouth", "Rochester", "Saint Cloud", "Saint Paul"],
  Mississippi: ["Biloxi", "Gulfport", "Hattiesburg", "Jackson", "Meridian", "Olive Branch", "Southaven", "Tupelo"],
  Missouri: ["Columbia", "Independence", "Kansas City", "Lee's Summit", "O'Fallon", "Saint Louis", "Springfield", "St. Joseph"],
  Montana: ["Billings", "Bozeman", "Butte", "Great Falls", "Havre", "Helena", "Kalispell", "Missoula"],
  Nebraska: ["Bellevue", "Fremont", "Grand Island", "Hastings", "Kearney", "Lincoln", "North Platte", "Omaha"],
  Nevada: ["Carson City", "Elko", "Fernley", "Henderson", "Las Vegas", "North Las Vegas", "Reno", "Sparks"],
  "New Hampshire": ["Concord", "Dover", "Hudson", "Manchester", "Merrimack", "Nashua", "Rochester", "Salem"],
  "New Jersey": ["Edison", "Elizabeth", "Jersey City", "Newark", "Paterson", "Toms River", "Trenton"],
  "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Roswell", "Santa Fe"],
  "New York": ["Albany", "Buffalo", "New York City", "Rochester", "Syracuse", "Yonkers"],
  "North Carolina": ["Charlotte", "Durham", "Fayetteville", "Greensboro", "Raleigh", "Winston-Salem"],
  "North Dakota": ["Bismarck", "Fargo", "Grand Forks", "Minot", "West Fargo"],
  Ohio: ["Akron", "Cincinnati", "Cleveland", "Columbus", "Dayton", "Toledo"],
  Oklahoma: ["Broken Arrow", "Lawton", "Norman", "Oklahoma City", "Tulsa"],
  Oregon: ["Bend", "Eugene", "Gresham", "Hillsboro", "Portland", "Salem"],
  Pennsylvania: ["Allentown", "Erie", "Harrisburg", "Philadelphia", "Pittsburgh", "Reading", "Scranton"],
  "Rhode Island": ["Cranston", "East Providence", "Pawtucket", "Providence", "Warwick"],
  "South Carolina": ["Charleston", "Columbia", "Greenville", "Mount Pleasant", "North Charleston"],
  "South Dakota": ["Aberdeen", "Brookings", "Rapid City", "Sioux Falls", "Watertown"],
  Tennessee: ["Chattanooga", "Clarksville", "Knoxville", "Memphis", "Nashville"],
  Texas: ["Arlington", "Austin", "Corpus Christi", "Dallas", "El Paso", "Fort Worth", "Houston", "Laredo", "Plano", "San Antonio"],
  Utah: ["Orem", "Provo", "Salt Lake City", "West Jordan", "West Valley City"],
  Vermont: ["Barre", "Burlington", "Montpelier", "Rutland", "South Burlington"],
  Virginia: ["Arlington", "Chesapeake", "Newport News", "Norfolk", "Richmond", "Virginia Beach"],
  Washington: ["Bellevue", "Kirkland", "Seattle", "Spokane", "Tacoma", "Vancouver"],
  "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  Wisconsin: ["Green Bay", "Kenosha", "Madison", "Milwaukee", "Racine"],
  Wyoming: ["Casper", "Cheyenne", "Gillette", "Laramie", "Rock Springs"],

  AB: ["Calgary", "Edmonton", "Lethbridge", "Medicine Hat", "Red Deer", "St. Albert"],
  BC: ["Abbotsford", "Burnaby", "Kelowna", "Richmond", "Surrey", "Vancouver", "Victoria"],
  MB: ["Brandon", "Steinbach", "Thompson", "Winnipeg"],
  NB: ["Fredericton", "Miramichi", "Moncton", "Saint John"],
  NL_CA: ["Corner Brook", "Gander", "Mount Pearl", "St. John's"],
  NS: ["Dartmouth", "Halifax", "Sydney", "Truro"],
  NT: ["Hay River", "Inuvik", "Yellowknife"],
  NU: ["Iqaluit", "Rankin Inlet"],
  ON: ["Brampton", "Hamilton", "Kitchener", "London", "Markham", "Mississauga", "Ottawa", "Toronto", "Vaughan", "Windsor"],
  PE: ["Charlottetown", "Stratford", "Summerside"],
  QC: ["Gatineau", "Laval", "Longueuil", "Montreal", "Quebec City", "Sherbrooke"],
  SK: ["Moose Jaw", "Prince Albert", "Regina", "Saskatoon"],
  YT: ["Dawson City", "Whitehorse"],

  ENG: ["Birmingham", "Bristol", "Leeds", "Leicester", "Liverpool", "London", "Manchester", "Newcastle", "Nottingham", "Sheffield"],
  SCT: ["Aberdeen", "Dundee", "Edinburgh", "Glasgow", "Inverness", "Stirling"],
  WLS: ["Bangor", "Cardiff", "Newport", "Swansea", "Wrexham"],
  NIR: ["Bangor", "Belfast", "Derry", "Lisburn", "Newry"],

  ACT: ["Belconnen", "Canberra", "Tuggeranong"],
  NSW: ["Central Coast", "Coffs Harbour", "Newcastle", "Sydney", "Wollongong"],
  NT_AU: ["Alice Springs", "Darwin", "Katherine", "Palmerston"],
  QLD: ["Brisbane", "Cairns", "Gold Coast", "Sunshine Coast", "Townsville"],
  SA_AU: ["Adelaide", "Mount Gambier", "Murray Bridge", "Whyalla"],
  TAS: ["Burnie", "Devonport", "Hobart", "Launceston"],
  VIC: ["Ballarat", "Bendigo", "Geelong", "Melbourne", "Shepparton"],
  WA: ["Bunbury", "Fremantle", "Joondalup", "Mandurah", "Perth"],

  BW: ["Freiburg", "Heidelberg", "Karlsruhe", "Mannheim", "Stuttgart"],
  BY: ["Augsburg", "Munich", "Nuremberg", "Regensburg", "Würzburg"],
  BE_DE: ["Berlin"],
  BB: ["Brandenburg an der Havel", "Cottbus", "Potsdam"],
  HB: ["Bremen", "Bremerhaven"],
  HH: ["Hamburg"],
  HE: ["Darmstadt", "Frankfurt", "Kassel", "Offenbach", "Wiesbaden"],
  MV: ["Neubrandenburg", "Rostock", "Schwerin"],
  NI_DE: ["Braunschweig", "Göttingen", "Hanover", "Oldenburg", "Osnabrück"],
  NW: ["Bonn", "Cologne", "Dortmund", "Duisburg", "Düsseldorf", "Essen", "Münster"],
  RP: ["Koblenz", "Ludwigshafen", "Mainz", "Trier"],
  SL_DE: ["Saarbrücken"],
  SN_DE: ["Chemnitz", "Dresden", "Leipzig"],
  ST_DE: ["Halle", "Magdeburg"],
  SH: ["Flensburg", "Kiel", "Lübeck"],
  TH_DE: ["Erfurt", "Jena", "Weimar"],

  ARA: ["Clermont-Ferrand", "Grenoble", "Lyon", "Saint-Étienne"],
  BFC: ["Besançon", "Dijon"],
  BRE: ["Brest", "Quimper", "Rennes", "Saint-Malo"],
  CVL: ["Blois", "Orléans", "Tours"],
  COR: ["Ajaccio", "Bastia"],
  GES: ["Metz", "Mulhouse", "Nancy", "Reims", "Strasbourg"],
  HDF: ["Amiens", "Dunkirk", "Lille", "Roubaix"],
  IDF: ["Boulogne-Billancourt", "Nanterre", "Paris", "Saint-Denis", "Versailles"],
  NOR: ["Caen", "Le Havre", "Rouen"],
  NAQ: ["Bordeaux", "La Rochelle", "Limoges", "Poitiers"],
  OCC: ["Montpellier", "Nîmes", "Perpignan", "Toulouse"],
  PAC: ["Aix-en-Provence", "Cannes", "Marseille", "Nice", "Toulon"],
  PDL: ["Angers", "Le Mans", "Nantes"],

  AP: ["Guntur", "Nellore", "Tirupati", "Vijayawada", "Visakhapatnam"],
  AR_IN: ["Itanagar"],
  AS: ["Dibrugarh", "Guwahati", "Silchar"],
  BR_IN: ["Gaya", "Muzaffarpur", "Patna"],
  CG_IN: ["Bhilai", "Bilaspur", "Raipur"],
  DL: ["Faridabad", "Ghaziabad", "Gurgaon", "New Delhi", "Noida"],
  GA_IN: ["Margao", "Panaji", "Vasco da Gama"],
  GJ: ["Ahmedabad", "Gandhinagar", "Rajkot", "Surat", "Vadodara"],
  HR_IN: ["Ambala", "Faridabad", "Gurgaon", "Karnal", "Panipat"],
  HP: ["Dharamshala", "Shimla"],
  JH: ["Dhanbad", "Jamshedpur", "Ranchi"],
  KA: ["Bangalore", "Belgaum", "Hubli", "Mangalore", "Mysore"],
  KL: ["Kochi", "Kozhikode", "Thiruvananthapuram", "Thrissur"],
  MP_IN: ["Bhopal", "Gwalior", "Indore", "Jabalpur"],
  MH: ["Mumbai", "Nagpur", "Nashik", "Navi Mumbai", "Pune", "Thane"],
  MN_IN: ["Imphal"],
  ML_IN: ["Shillong"],
  MZ_IN: ["Aizawl"],
  NL_IN: ["Kohima"],
  OD: ["Bhubaneswar", "Cuttack", "Rourkela"],
  PB: ["Amritsar", "Jalandhar", "Ludhiana", "Patiala"],
  RJ: ["Ajmer", "Bikaner", "Jaipur", "Jodhpur", "Kota", "Udaipur"],
  SK_IN: ["Gangtok"],
  TN: ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli"],
  TS: ["Hyderabad", "Karimnagar", "Nizamabad", "Warangal"],
  TR_IN: ["Agartala"],
  UP: ["Agra", "Allahabad", "Kanpur", "Lucknow", "Meerut", "Varanasi"],
  UK_IN: ["Dehradun", "Haridwar"],
  WB: ["Asansol", "Durgapur", "Howrah", "Kolkata", "Siliguri"],

  JP13: ["Chiyoda", "Minato", "Shibuya", "Shinjuku", "Tokyo"],
  JP27: ["Higashiosaka", "Osaka", "Sakai"],
  JP23: ["Nagoya", "Okazaki", "Toyota"],
  JP14: ["Kawasaki", "Sagamihara", "Yokohama"],
  JP11: ["Kawagoe", "Kawaguchi", "Saitama"],
  JP12: ["Chiba", "Funabashi", "Kashiwa"],
  JP01: ["Asahikawa", "Hakodate", "Sapporo"],
  JP40: ["Fukuoka", "Kitakyushu"],
  JP26: ["Kyoto"],
  JP28: ["Himeji", "Kobe", "Nishinomiya"],

  AGU: ["Aguascalientes"],
  BCN: ["Ensenada", "Mexicali", "Tijuana"],
  CMX: ["Mexico City"],
  JAL: ["Guadalajara", "Tlaquepaque", "Zapopan"],
  NLE: ["Monterrey", "San Nicolás", "San Pedro Garza García"],
  GUA: ["Celaya", "Irapuato", "León"],
  PUE: ["Puebla", "Tehuacán"],
  QUE: ["Querétaro"],
  YUC: ["Mérida"],

  SP: ["Campinas", "Guarulhos", "Ribeirão Preto", "Santos", "São Paulo"],
  RJ_BR: ["Niterói", "Petrópolis", "Rio de Janeiro"],
  MG_BR: ["Belo Horizonte", "Juiz de Fora", "Uberlândia"],
  BA: ["Feira de Santana", "Salvador"],
  RS: ["Caxias do Sul", "Pelotas", "Porto Alegre"],
  PR_BR: ["Curitiba", "Londrina", "Maringá"],
  PE_BR: ["Jaboatão", "Olinda", "Recife"],
  CE: ["Fortaleza", "Juazeiro do Norte"],
  DF_BR: ["Brasília"],
  SC_BR: ["Blumenau", "Florianópolis", "Joinville"],
  GO: ["Aparecida de Goiânia", "Goiânia"],

  LAZ: ["Frosinone", "Latina", "Rome"],
  LOM: ["Bergamo", "Brescia", "Milan", "Monza"],
  CAM_IT: ["Caserta", "Naples", "Salerno"],
  SIC: ["Catania", "Messina", "Palermo"],
  VEN: ["Padua", "Venice", "Verona", "Vicenza"],
  PIE: ["Alessandria", "Novara", "Turin"],
  EMR: ["Bologna", "Modena", "Parma", "Rimini"],
  TOS: ["Florence", "Livorno", "Pisa", "Siena"],

  MD_ES: ["Alcalá de Henares", "Getafe", "Madrid"],
  CT: ["Barcelona", "Girona", "Tarragona"],
  AN_ES: ["Córdoba", "Granada", "Málaga", "Seville"],
  VC_ES: ["Alicante", "Castellón", "Valencia"],

  NH: ["Amsterdam", "Haarlem", "Hilversum"],
  ZH_NL: ["Delft", "Leiden", "Rotterdam", "The Hague"],
  NB_NL: ["Breda", "Eindhoven", "Tilburg"],
  GE_NL: ["Apeldoorn", "Arnhem", "Nijmegen"],
  UT_NL: ["Amersfoort", "Utrecht"],

  ZH_CH: ["Winterthur", "Zürich"],
  BE_CH: ["Bern", "Biel", "Thun"],
  VD: ["Lausanne", "Montreux", "Nyon"],
  GE_CH: ["Geneva"],
  LU_CH: ["Lucerne"],
  BS_CH: ["Basel"],
  TI: ["Bellinzona", "Lugano"],

  AUH: ["Abu Dhabi", "Al Ain"],
  DXB: ["Dubai", "Jebel Ali"],
  SHJ: ["Sharjah"],
  RAK: ["Ras al-Khaimah"],
  AJM: ["Ajman"],
  FUJ: ["Fujairah"],

  GP: ["Johannesburg", "Pretoria", "Sandton", "Soweto"],
  WC: ["Cape Town", "Paarl", "Stellenbosch"],
  KZN: ["Durban", "Pietermaritzburg", "Richards Bay"],
  EC_ZA: ["East London", "Port Elizabeth"],
  FS: ["Bloemfontein"],
  LP: ["Polokwane"],
  NW_ZA: ["Rustenburg"],

  SEL: ["Seoul"],
  PUS: ["Busan"],
  ICN: ["Incheon"],
  GGD: ["Goyang", "Seongnam", "Suwon", "Yongin"],
  DGU: ["Daegu"],
  DJN: ["Daejeon"],
  GWJ: ["Gwangju"],

  BJ_CN: ["Beijing"],
  SH_CN: ["Shanghai"],
  GD_CN: ["Dongguan", "Foshan", "Guangzhou", "Shenzhen", "Zhuhai"],
  ZJ_CN: ["Hangzhou", "Ningbo", "Wenzhou"],
  JS_CN: ["Nanjing", "Suzhou", "Wuxi"],
  SN_CN: ["Baoji", "Xi'an", "Xianyang"],
  SD_CN: ["Jinan", "Qingdao"],
  HEB: ["Shijiazhuang", "Tangshan"],
  SC_CN: ["Chengdu", "Mianyang"],
  FJ_CN: ["Fuzhou", "Xiamen"],
  HN_CN: ["Changsha", "Zhuzhou"],

  LA_NG: ["Ikeja", "Lagos", "Lekki"],
  ABJ: ["Abuja"],
  KN_NG: ["Kano"],
  RV: ["Port Harcourt"],
  OG: ["Abeokuta"],
  OY: ["Ibadan"],

  NCR: ["Makati", "Manila", "Pasig", "Quezon City", "Taguig"],
  CEB: ["Cebu City", "Lapu-Lapu", "Mandaue"],
  DVO: ["Davao City"],
  ILO_PH: ["Iloilo City"],
  BUL: ["Malolos", "Meycauayan"],
  CAV: ["Bacoor", "Dasmariñas", "Imus"],
  LAG_PH: ["Calamba", "San Pedro", "Santa Rosa"],

  IST: ["Istanbul"],
  ANK: ["Ankara"],
  IZM: ["Izmir"],
  ANT_TR: ["Antalya"],
  BRS_TR: ["Bursa"],
  ADN: ["Adana"],

  MZ_PL: ["Warsaw"],
  ML_PL: ["Kraków"],
  WP_PL: ["Poznań"],
  DS_PL: ["Wrocław"],
  SL_PL: ["Katowice"],
  PM_PL: ["Gdańsk"],

  BOG: ["Bogotá"],
  ANT_CO: ["Medellín"],
  VAL_CO: ["Cali"],
  ATL_CO: ["Barranquilla"],
  SAN_CO: ["Bucaramanga"],

  CABA: ["Buenos Aires"],
  BA_AR: ["La Plata", "Mar del Plata"],
  COR_AR: ["Córdoba"],
  SFE: ["Rosario", "Santa Fe"],
  MZA: ["Mendoza"],
  TUC: ["San Miguel de Tucumán"],

  AKL: ["Auckland"],
  WGN: ["Wellington"],
  CAN_NZ: ["Christchurch"],
  WKO: ["Hamilton"],
  OTA: ["Dunedin", "Queenstown"],
  BOP: ["Tauranga"],

  RYD: ["Riyadh"],
  MKH: ["Jeddah", "Mecca"],
  ESH_SA: ["Al Khobar", "Dammam", "Dhahran"],
  MDN: ["Madinah"],

  TA: ["Bnei Brak", "Ramat Gan", "Tel Aviv"],
  JM_IL: ["Jerusalem"],
  HFA: ["Haifa"],
  CTR_IL: ["Petah Tikva", "Rishon LeZion"],

  STK: ["Stockholm"],
  VGT: ["Gothenburg"],
  SKN: ["Malmö"],

  OSL: ["Oslo"],
  VKN: ["Bergen"],
  TRO_NO: ["Trondheim"],

  CPH: ["Copenhagen"],
  SDK: ["Odense"],
  MDJ: ["Aarhus"],

  DUB: ["Dublin"],
  CRK: ["Cork"],
  GAL_IE: ["Galway"],
  LMK: ["Limerick"],

  SG_C: ["Singapore Central"],
  SG_N: ["Woodlands", "Yishun"],
  SG_E: ["Bedok", "Tampines"],
  SG_W: ["Clementi", "Jurong"],
  SG_NE: ["Punggol", "Sengkang"],

  HKI: ["Causeway Bay", "Central", "Wan Chai"],
  KLN: ["Kowloon Bay", "Mong Kok", "Tsim Sha Tsui"],
  NTR: ["Sha Tin", "Tsuen Wan", "Tuen Mun"],

  MOW: ["Moscow"],
  SPE: ["Saint Petersburg"],
  NVS: ["Novosibirsk"],
  SVE: ["Yekaterinburg"],
  KDA: ["Krasnodar", "Sochi"],
  TAT: ["Kazan"],

  PB_PK: ["Faisalabad", "Lahore", "Rawalpindi"],
  SD_PK: ["Karachi"],
  ICT: ["Islamabad"],
  KP_PK: ["Peshawar"],

  DHK: ["Dhaka"],
  CHT: ["Chittagong"],
  KHU: ["Khulna"],
  RAJ_BD: ["Rajshahi"],
  SYL: ["Sylhet"],

  CAI: ["Cairo"],
  ALX: ["Alexandria"],
  GZ_EG: ["Giza"],
  LUX: ["Luxor"],

  NRB: ["Nairobi"],
  CST_KE: ["Mombasa"],
  RVP: ["Nakuru"],

  GAR: ["Accra", "Tema"],
  ASH: ["Kumasi"],

  DOH: ["Doha"],
  RYN: ["Al Rayyan"],

  KWT: ["Kuwait City"],
  AHM: ["Ahmadi"],

  WIE: ["Vienna"],
  STM: ["Graz"],
  OOE: ["Linz"],
  SBG: ["Salzburg"],
  TIR: ["Innsbruck"],

  LIS: ["Lisbon"],
  PRT: ["Porto"],
  FAR_PT: ["Faro"],

  ATT: ["Athens", "Piraeus"],
  CMC: ["Thessaloniki"],
  CRE: ["Heraklion"],

  BUC: ["Bucharest"],
  CLJ: ["Cluj-Napoca"],
  TIM: ["Timișoara"],

  BUD: ["Budapest"],
  PES: ["Debrecen"],

  PHA: ["Prague"],
  JMK: ["Brno"],

  BKK: ["Bangkok"],
  CNX: ["Chiang Mai"],
  PKT: ["Phuket"],

  KUL: ["Kuala Lumpur"],
  SGR: ["Shah Alam"],
  PNG: ["George Town"],
  JHR: ["Johor Bahru"],

  JK: ["Jakarta"],
  JI: ["Bandung"],
  JT: ["Semarang"],
  JB: ["Surabaya"],
  BA_ID: ["Denpasar"],

  HAN: ["Hanoi"],
  HCM: ["Ho Chi Minh City"],
  DAN: ["Da Nang"],

  KBP: ["Kyiv"],
  LWO: ["Lviv"],
  ODS: ["Odesa"],

  LIM: ["Lima"],
  CUS: ["Cusco"],
  ARE_PE: ["Arequipa"],

  RM: ["Santiago"],
  VAP: ["Valparaíso", "Viña del Mar"],
  BIO: ["Concepción"],

  SJ_CR: ["San José"],
  PAN: ["Panama City"],
  KNG: ["Kingston"],
  SAN_JM: ["Saint Andrew"],
  POS: ["Port of Spain"],
  SFD: ["San Fernando"],

  HEL: ["Espoo", "Helsinki", "Vantaa"],
  PIR: ["Tampere"],

  BRU: ["Brussels"],
  FLA: ["Antwerp", "Ghent"],
  WAL: ["Liège", "Namur"],

  TPE: ["Taipei"],
  KHH: ["Kaohsiung"],
  TNN: ["Tainan"],
};

export function getCountries(): LocationOption[] {
  return COUNTRIES;
}

export function getStates(countryCode: string): LocationOption[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}

export function getCities(stateCode: string): string[] {
  return CITIES_BY_STATE[stateCode] ?? [];
}

export function getStateLabel(countryCode: string): string {
  switch (countryCode) {
    case "US": return "State";
    case "CA": return "Province";
    case "AU": return "State / Territory";
    case "GB": return "Country / Region";
    case "JP": return "Prefecture";
    case "CH": return "Canton";
    case "DE": return "Bundesland";
    case "BR": return "Estado";
    default: return "State / Region";
  }
}
