export interface LocationOption {
  code: string;
  label: string;
}

const COUNTRIES: LocationOption[] = [
  { code: "AF", label: "Afghanistan" },
  { code: "AL", label: "Albania" },
  { code: "DZ", label: "Algeria" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AG", label: "Antigua and Barbuda" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaijan" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Bahrain" },
  { code: "BD", label: "Bangladesh" },
  { code: "BB", label: "Barbados" },
  { code: "BY", label: "Belarus" },
  { code: "BE", label: "Belgium" },
  { code: "BZ", label: "Belize" },
  { code: "BJ", label: "Benin" },
  { code: "BT", label: "Bhutan" },
  { code: "BO", label: "Bolivia" },
  { code: "BA", label: "Bosnia and Herzegovina" },
  { code: "BW", label: "Botswana" },
  { code: "BR", label: "Brazil" },
  { code: "BN", label: "Brunei" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KH", label: "Cambodia" },
  { code: "CM", label: "Cameroon" },
  { code: "CA", label: "Canada" },
  { code: "CF", label: "Central African Republic" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoros" },
  { code: "CG", label: "Congo" },
  { code: "CD", label: "Congo (DRC)" },
  { code: "CR", label: "Costa Rica" },
  { code: "CI", label: "Côte d'Ivoire" },
  { code: "HR", label: "Croatia" },
  { code: "CU", label: "Cuba" },
  { code: "CY", label: "Cyprus" },
  { code: "CZ", label: "Czech Republic" },
  { code: "DK", label: "Denmark" },
  { code: "DJ", label: "Djibouti" },
  { code: "DM", label: "Dominica" },
  { code: "DO", label: "Dominican Republic" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egypt" },
  { code: "SV", label: "El Salvador" },
  { code: "GQ", label: "Equatorial Guinea" },
  { code: "ER", label: "Eritrea" },
  { code: "EE", label: "Estonia" },
  { code: "SZ", label: "Eswatini" },
  { code: "ET", label: "Ethiopia" },
  { code: "FJ", label: "Fiji" },
  { code: "FI", label: "Finland" },
  { code: "FR", label: "France" },
  { code: "GA", label: "Gabon" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "DE", label: "Germany" },
  { code: "GH", label: "Ghana" },
  { code: "GR", label: "Greece" },
  { code: "GD", label: "Grenada" },
  { code: "GT", label: "Guatemala" },
  { code: "GN", label: "Guinea" },
  { code: "GW", label: "Guinea-Bissau" },
  { code: "GY", label: "Guyana" },
  { code: "HT", label: "Haiti" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hungary" },
  { code: "IS", label: "Iceland" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IR", label: "Iran" },
  { code: "IQ", label: "Iraq" },
  { code: "IE", label: "Ireland" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italy" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japan" },
  { code: "JO", label: "Jordan" },
  { code: "KZ", label: "Kazakhstan" },
  { code: "KE", label: "Kenya" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "KG", label: "Kyrgyzstan" },
  { code: "LA", label: "Laos" },
  { code: "LV", label: "Latvia" },
  { code: "LB", label: "Lebanon" },
  { code: "LS", label: "Lesotho" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libya" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lithuania" },
  { code: "LU", label: "Luxembourg" },
  { code: "MO", label: "Macau" },
  { code: "MG", label: "Madagascar" },
  { code: "MW", label: "Malawi" },
  { code: "MY", label: "Malaysia" },
  { code: "MV", label: "Maldives" },
  { code: "ML", label: "Mali" },
  { code: "MT", label: "Malta" },
  { code: "MH", label: "Marshall Islands" },
  { code: "MR", label: "Mauritania" },
  { code: "MU", label: "Mauritius" },
  { code: "MX", label: "Mexico" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldova" },
  { code: "MC", label: "Monaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MA", label: "Morocco" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NL", label: "Netherlands" },
  { code: "NZ", label: "New Zealand" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Niger" },
  { code: "NG", label: "Nigeria" },
  { code: "KP", label: "North Korea" },
  { code: "MK", label: "North Macedonia" },
  { code: "NO", label: "Norway" },
  { code: "OM", label: "Oman" },
  { code: "PK", label: "Pakistan" },
  { code: "PW", label: "Palau" },
  { code: "PS", label: "Palestine" },
  { code: "PA", label: "Panama" },
  { code: "PG", label: "Papua New Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Peru" },
  { code: "PH", label: "Philippines" },
  { code: "PL", label: "Poland" },
  { code: "PT", label: "Portugal" },
  { code: "PR", label: "Puerto Rico" },
  { code: "QA", label: "Qatar" },
  { code: "RO", label: "Romania" },
  { code: "RU", label: "Russia" },
  { code: "RW", label: "Rwanda" },
  { code: "KN", label: "Saint Kitts and Nevis" },
  { code: "LC", label: "Saint Lucia" },
  { code: "VC", label: "Saint Vincent and the Grenadines" },
  { code: "WS", label: "Samoa" },
  { code: "SM", label: "San Marino" },
  { code: "ST", label: "São Tomé and Príncipe" },
  { code: "SA", label: "Saudi Arabia" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leone" },
  { code: "SG", label: "Singapore" },
  { code: "SK", label: "Slovakia" },
  { code: "SI", label: "Slovenia" },
  { code: "SB", label: "Solomon Islands" },
  { code: "SO", label: "Somalia" },
  { code: "ZA", label: "South Africa" },
  { code: "KR", label: "South Korea" },
  { code: "SS", label: "South Sudan" },
  { code: "ES", label: "Spain" },
  { code: "LK", label: "Sri Lanka" },
  { code: "SD", label: "Sudan" },
  { code: "SR", label: "Suriname" },
  { code: "SE", label: "Sweden" },
  { code: "CH", label: "Switzerland" },
  { code: "SY", label: "Syria" },
  { code: "TW", label: "Taiwan" },
  { code: "TJ", label: "Tajikistan" },
  { code: "TZ", label: "Tanzania" },
  { code: "TH", label: "Thailand" },
  { code: "TL", label: "Timor-Leste" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad and Tobago" },
  { code: "TN", label: "Tunisia" },
  { code: "TR", label: "Turkey" },
  { code: "TM", label: "Turkmenistan" },
  { code: "TV", label: "Tuvalu" },
  { code: "UG", label: "Uganda" },
  { code: "UA", label: "Ukraine" },
  { code: "AE", label: "United Arab Emirates" },
  { code: "GB", label: "United Kingdom" },
  { code: "US", label: "United States" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistan" },
  { code: "VU", label: "Vanuatu" },
  { code: "VA", label: "Vatican City" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yemen" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabwe" },
];

function alpha(arr: LocationOption[]): LocationOption[] {
  return [...arr].sort((a, b) => a.label.localeCompare(b.label));
}

function alphaStrings(arr: string[]): string[] {
  return [...arr].sort((a, b) => a.localeCompare(b));
}

const US_STATES: LocationOption[] = alpha([
  "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware",
  "District of Columbia","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa",
  "Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota",
  "Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey",
  "New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
  "Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah",
  "Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming",
].map((s) => ({ code: s, label: s })));

const STATES_BY_COUNTRY: Record<string, LocationOption[]> = {
  US: US_STATES,

  CA: alpha([
    { code: "AB", label: "Alberta" },
    { code: "BC", label: "British Columbia" },
    { code: "MB", label: "Manitoba" },
    { code: "NB", label: "New Brunswick" },
    { code: "NL_CA", label: "Newfoundland and Labrador" },
    { code: "NS", label: "Nova Scotia" },
    { code: "NT", label: "Northwest Territories" },
    { code: "NU", label: "Nunavut" },
    { code: "ON", label: "Ontario" },
    { code: "PE", label: "Prince Edward Island" },
    { code: "QC", label: "Quebec" },
    { code: "SK", label: "Saskatchewan" },
    { code: "YT", label: "Yukon" },
  ]),

  GB: alpha([
    { code: "ENG", label: "England" },
    { code: "NIR", label: "Northern Ireland" },
    { code: "SCT", label: "Scotland" },
    { code: "WLS", label: "Wales" },
  ]),

  AU: alpha([
    { code: "ACT", label: "Australian Capital Territory" },
    { code: "NSW", label: "New South Wales" },
    { code: "NT_AU", label: "Northern Territory" },
    { code: "QLD", label: "Queensland" },
    { code: "SA_AU", label: "South Australia" },
    { code: "TAS", label: "Tasmania" },
    { code: "VIC", label: "Victoria" },
    { code: "WA", label: "Western Australia" },
  ]),

  DE: alpha([
    { code: "BW", label: "Baden-Württemberg" },
    { code: "BY", label: "Bavaria" },
    { code: "BE_DE", label: "Berlin" },
    { code: "BB", label: "Brandenburg" },
    { code: "HB", label: "Bremen" },
    { code: "HH", label: "Hamburg" },
    { code: "HE", label: "Hesse" },
    { code: "NI_DE", label: "Lower Saxony" },
    { code: "MV", label: "Mecklenburg-Vorpommern" },
    { code: "NW", label: "North Rhine-Westphalia" },
    { code: "RP", label: "Rhineland-Palatinate" },
    { code: "SL_DE", label: "Saarland" },
    { code: "SN_DE", label: "Saxony" },
    { code: "ST_DE", label: "Saxony-Anhalt" },
    { code: "SH", label: "Schleswig-Holstein" },
    { code: "TH_DE", label: "Thuringia" },
  ]),

  FR: alpha([
    { code: "ARA", label: "Auvergne-Rhône-Alpes" },
    { code: "BFC", label: "Bourgogne-Franche-Comté" },
    { code: "BRE", label: "Brittany" },
    { code: "CVL", label: "Centre-Val de Loire" },
    { code: "COR", label: "Corsica" },
    { code: "GES", label: "Grand Est" },
    { code: "HDF", label: "Hauts-de-France" },
    { code: "IDF", label: "Île-de-France" },
    { code: "NOR", label: "Normandy" },
    { code: "NAQ", label: "Nouvelle-Aquitaine" },
    { code: "OCC", label: "Occitanie" },
    { code: "PDL", label: "Pays de la Loire" },
    { code: "PAC", label: "Provence-Alpes-Côte d'Azur" },
  ]),

  IN: alpha([
    { code: "AP", label: "Andhra Pradesh" },
    { code: "AR_IN", label: "Arunachal Pradesh" },
    { code: "AS", label: "Assam" },
    { code: "BR_IN", label: "Bihar" },
    { code: "CG_IN", label: "Chhattisgarh" },
    { code: "DL", label: "Delhi" },
    { code: "GA_IN", label: "Goa" },
    { code: "GJ", label: "Gujarat" },
    { code: "HR_IN", label: "Haryana" },
    { code: "HP", label: "Himachal Pradesh" },
    { code: "JH", label: "Jharkhand" },
    { code: "KA", label: "Karnataka" },
    { code: "KL", label: "Kerala" },
    { code: "MP_IN", label: "Madhya Pradesh" },
    { code: "MH", label: "Maharashtra" },
    { code: "MN_IN", label: "Manipur" },
    { code: "ML_IN", label: "Meghalaya" },
    { code: "MZ_IN", label: "Mizoram" },
    { code: "NL_IN", label: "Nagaland" },
    { code: "OD", label: "Odisha" },
    { code: "PB", label: "Punjab" },
    { code: "RJ", label: "Rajasthan" },
    { code: "SK_IN", label: "Sikkim" },
    { code: "TN", label: "Tamil Nadu" },
    { code: "TS", label: "Telangana" },
    { code: "TR_IN", label: "Tripura" },
    { code: "UP", label: "Uttar Pradesh" },
    { code: "UK_IN", label: "Uttarakhand" },
    { code: "WB", label: "West Bengal" },
  ]),

  JP: alpha([
    { code: "JP23", label: "Aichi" },
    { code: "JP12", label: "Chiba" },
    { code: "JP40", label: "Fukuoka" },
    { code: "JP01", label: "Hokkaido" },
    { code: "JP28", label: "Hyogo" },
    { code: "JP14", label: "Kanagawa" },
    { code: "JP26", label: "Kyoto" },
    { code: "JP27", label: "Osaka" },
    { code: "JP11", label: "Saitama" },
    { code: "JP13", label: "Tokyo" },
  ]),

  MX: alpha([
    { code: "AGU", label: "Aguascalientes" },
    { code: "BCN", label: "Baja California" },
    { code: "BCS", label: "Baja California Sur" },
    { code: "CAM_MX", label: "Campeche" },
    { code: "CHP", label: "Chiapas" },
    { code: "CHH", label: "Chihuahua" },
    { code: "CMX", label: "Ciudad de México" },
    { code: "COA", label: "Coahuila" },
    { code: "COL_MX", label: "Colima" },
    { code: "DUR", label: "Durango" },
    { code: "MEX", label: "Estado de México" },
    { code: "GUA", label: "Guanajuato" },
    { code: "GRO", label: "Guerrero" },
    { code: "HID", label: "Hidalgo" },
    { code: "JAL", label: "Jalisco" },
    { code: "MIC", label: "Michoacán" },
    { code: "MOR", label: "Morelos" },
    { code: "NAY", label: "Nayarit" },
    { code: "NLE", label: "Nuevo León" },
    { code: "OAX", label: "Oaxaca" },
    { code: "PUE", label: "Puebla" },
    { code: "QUE", label: "Querétaro" },
    { code: "ROO", label: "Quintana Roo" },
    { code: "SLP", label: "San Luis Potosí" },
    { code: "SIN", label: "Sinaloa" },
    { code: "SON", label: "Sonora" },
    { code: "TAB", label: "Tabasco" },
    { code: "TAM", label: "Tamaulipas" },
    { code: "TLA", label: "Tlaxcala" },
    { code: "VER", label: "Veracruz" },
    { code: "YUC", label: "Yucatán" },
    { code: "ZAC", label: "Zacatecas" },
  ]),

  BR: alpha([
    { code: "AC", label: "Acre" },
    { code: "AL_BR", label: "Alagoas" },
    { code: "AP_BR", label: "Amapá" },
    { code: "AM", label: "Amazonas" },
    { code: "BA", label: "Bahia" },
    { code: "CE", label: "Ceará" },
    { code: "DF_BR", label: "Distrito Federal" },
    { code: "ES_BR", label: "Espírito Santo" },
    { code: "GO", label: "Goiás" },
    { code: "MA_BR", label: "Maranhão" },
    { code: "MT", label: "Mato Grosso" },
    { code: "MS", label: "Mato Grosso do Sul" },
    { code: "MG_BR", label: "Minas Gerais" },
    { code: "PA_BR", label: "Pará" },
    { code: "PB_BR", label: "Paraíba" },
    { code: "PR_BR", label: "Paraná" },
    { code: "PE_BR", label: "Pernambuco" },
    { code: "PI", label: "Piauí" },
    { code: "RJ_BR", label: "Rio de Janeiro" },
    { code: "RN", label: "Rio Grande do Norte" },
    { code: "RS", label: "Rio Grande do Sul" },
    { code: "RO_BR", label: "Rondônia" },
    { code: "RR", label: "Roraima" },
    { code: "SC_BR", label: "Santa Catarina" },
    { code: "SP", label: "São Paulo" },
    { code: "SE_BR", label: "Sergipe" },
    { code: "TO_BR", label: "Tocantins" },
  ]),

  IT: alpha([
    { code: "ABR", label: "Abruzzo" },
    { code: "BAS", label: "Basilicata" },
    { code: "CAL", label: "Calabria" },
    { code: "CAM_IT", label: "Campania" },
    { code: "EMR", label: "Emilia-Romagna" },
    { code: "FVG", label: "Friuli Venezia Giulia" },
    { code: "LAZ", label: "Lazio" },
    { code: "LIG", label: "Liguria" },
    { code: "LOM", label: "Lombardy" },
    { code: "MAR", label: "Marche" },
    { code: "MOL", label: "Molise" },
    { code: "PIE", label: "Piedmont" },
    { code: "PUG", label: "Puglia" },
    { code: "SAR", label: "Sardinia" },
    { code: "SIC", label: "Sicily" },
    { code: "TOS", label: "Tuscany" },
    { code: "TAA", label: "Trentino-Alto Adige" },
    { code: "UMB", label: "Umbria" },
    { code: "VDA", label: "Valle d'Aosta" },
    { code: "VEN", label: "Veneto" },
  ]),

  ES: alpha([
    { code: "AN_ES", label: "Andalusia" },
    { code: "AR_ES", label: "Aragon" },
    { code: "AS_ES", label: "Asturias" },
    { code: "IB", label: "Balearic Islands" },
    { code: "PV", label: "Basque Country" },
    { code: "CN_ES", label: "Canary Islands" },
    { code: "CB", label: "Cantabria" },
    { code: "CM_ES", label: "Castilla-La Mancha" },
    { code: "CL_ES", label: "Castile and León" },
    { code: "CT", label: "Catalonia" },
    { code: "EX", label: "Extremadura" },
    { code: "GA_ES", label: "Galicia" },
    { code: "RI", label: "La Rioja" },
    { code: "MD_ES", label: "Madrid" },
    { code: "MU", label: "Murcia" },
    { code: "NA_ES", label: "Navarre" },
    { code: "VC_ES", label: "Valencia" },
  ]),

  NL: alpha([
    { code: "DR", label: "Drenthe" },
    { code: "FL", label: "Flevoland" },
    { code: "FR_NL", label: "Friesland" },
    { code: "GE_NL", label: "Gelderland" },
    { code: "GR_NL", label: "Groningen" },
    { code: "LI_NL", label: "Limburg" },
    { code: "NB_NL", label: "North Brabant" },
    { code: "NH", label: "North Holland" },
    { code: "OV", label: "Overijssel" },
    { code: "ZH_NL", label: "South Holland" },
    { code: "UT_NL", label: "Utrecht" },
    { code: "ZE", label: "Zeeland" },
  ]),

  CH: alpha([
    { code: "AG", label: "Aargau" },
    { code: "AI", label: "Appenzell Innerrhoden" },
    { code: "AR_CH", label: "Appenzell Ausserrhoden" },
    { code: "BS_CH", label: "Basel-Stadt" },
    { code: "BL", label: "Basel-Landschaft" },
    { code: "BE_CH", label: "Bern" },
    { code: "FR_CH", label: "Fribourg" },
    { code: "GE_CH", label: "Geneva" },
    { code: "GL", label: "Glarus" },
    { code: "GR_CH", label: "Graubünden" },
    { code: "JU", label: "Jura" },
    { code: "LU_CH", label: "Lucerne" },
    { code: "NE_CH", label: "Neuchâtel" },
    { code: "NW_CH", label: "Nidwalden" },
    { code: "OW", label: "Obwalden" },
    { code: "SG", label: "St. Gallen" },
    { code: "SH_CH", label: "Schaffhausen" },
    { code: "SZ", label: "Schwyz" },
    { code: "SO", label: "Solothurn" },
    { code: "TG", label: "Thurgau" },
    { code: "TI", label: "Ticino" },
    { code: "UR", label: "Uri" },
    { code: "VS", label: "Valais" },
    { code: "VD", label: "Vaud" },
    { code: "ZG", label: "Zug" },
    { code: "ZH_CH", label: "Zürich" },
  ]),

  AE: alpha([
    { code: "AUH", label: "Abu Dhabi" },
    { code: "AJM", label: "Ajman" },
    { code: "DXB", label: "Dubai" },
    { code: "FUJ", label: "Fujairah" },
    { code: "RAK", label: "Ras al-Khaimah" },
    { code: "SHJ", label: "Sharjah" },
    { code: "UAQ", label: "Umm al-Quwain" },
  ]),

  ZA: alpha([
    { code: "EC_ZA", label: "Eastern Cape" },
    { code: "FS", label: "Free State" },
    { code: "GP", label: "Gauteng" },
    { code: "KZN", label: "KwaZulu-Natal" },
    { code: "LP", label: "Limpopo" },
    { code: "MP_ZA", label: "Mpumalanga" },
    { code: "NC_ZA", label: "Northern Cape" },
    { code: "NW_ZA", label: "North West" },
    { code: "WC", label: "Western Cape" },
  ]),

  KR: alpha([
    { code: "PUS", label: "Busan" },
    { code: "DGU", label: "Daegu" },
    { code: "DJN", label: "Daejeon" },
    { code: "GGD", label: "Gyeonggi-do" },
    { code: "GWJ", label: "Gwangju" },
    { code: "ICN", label: "Incheon" },
    { code: "SEL", label: "Seoul" },
  ]),

  CN: alpha([
    { code: "BJ_CN", label: "Beijing" },
    { code: "CQ", label: "Chongqing" },
    { code: "FJ_CN", label: "Fujian" },
    { code: "GD_CN", label: "Guangdong" },
    { code: "GX", label: "Guangxi" },
    { code: "GZ_CN", label: "Guizhou" },
    { code: "HI_CN", label: "Hainan" },
    { code: "HEB", label: "Hebei" },
    { code: "HLJ", label: "Heilongjiang" },
    { code: "HEN", label: "Henan" },
    { code: "HUB", label: "Hubei" },
    { code: "HN_CN", label: "Hunan" },
    { code: "NMG", label: "Inner Mongolia" },
    { code: "JS_CN", label: "Jiangsu" },
    { code: "JX", label: "Jiangxi" },
    { code: "JL", label: "Jilin" },
    { code: "LN", label: "Liaoning" },
    { code: "NX", label: "Ningxia" },
    { code: "QH", label: "Qinghai" },
    { code: "SN_CN", label: "Shaanxi" },
    { code: "SD_CN", label: "Shandong" },
    { code: "SH_CN", label: "Shanghai" },
    { code: "SX", label: "Shanxi" },
    { code: "SC_CN", label: "Sichuan" },
    { code: "TJ_CN", label: "Tianjin" },
    { code: "XZ", label: "Tibet" },
    { code: "XJ", label: "Xinjiang" },
    { code: "YN", label: "Yunnan" },
    { code: "ZJ_CN", label: "Zhejiang" },
  ]),

  NG: alpha([
    { code: "ABJ", label: "Abuja (FCT)" },
    { code: "KN_NG", label: "Kano" },
    { code: "LA_NG", label: "Lagos" },
    { code: "OG", label: "Ogun" },
    { code: "OY", label: "Oyo" },
    { code: "RV", label: "Rivers" },
  ]),

  PH: alpha([
    { code: "BUL", label: "Bulacan" },
    { code: "CAV", label: "Cavite" },
    { code: "CEB", label: "Cebu" },
    { code: "DVO", label: "Davao" },
    { code: "ILO_PH", label: "Iloilo" },
    { code: "LAG_PH", label: "Laguna" },
    { code: "NCR", label: "Metro Manila (NCR)" },
  ]),

  TR: alpha([
    { code: "ADN", label: "Adana" },
    { code: "ANK", label: "Ankara" },
    { code: "ANT_TR", label: "Antalya" },
    { code: "BRS_TR", label: "Bursa" },
    { code: "IST", label: "Istanbul" },
    { code: "IZM", label: "Izmir" },
  ]),

  PL: alpha([
    { code: "DS_PL", label: "Lower Silesia" },
    { code: "KP", label: "Kuyavia-Pomerania" },
    { code: "LD", label: "Łódź" },
    { code: "ML_PL", label: "Lesser Poland" },
    { code: "MZ_PL", label: "Masovia (Warsaw)" },
    { code: "PM_PL", label: "Pomerania" },
    { code: "SL_PL", label: "Silesia" },
    { code: "WP_PL", label: "Greater Poland" },
  ]),

  CO: alpha([
    { code: "ANT_CO", label: "Antioquia" },
    { code: "ATL_CO", label: "Atlántico" },
    { code: "BOG", label: "Bogotá D.C." },
    { code: "SAN_CO", label: "Santander" },
    { code: "VAL_CO", label: "Valle del Cauca" },
  ]),

  AR: alpha([
    { code: "CABA", label: "Buenos Aires (City)" },
    { code: "BA_AR", label: "Buenos Aires (Province)" },
    { code: "COR_AR", label: "Córdoba" },
    { code: "MZA", label: "Mendoza" },
    { code: "SFE", label: "Santa Fe" },
    { code: "TUC", label: "Tucumán" },
  ]),

  NZ: alpha([
    { code: "AKL", label: "Auckland" },
    { code: "BOP", label: "Bay of Plenty" },
    { code: "CAN_NZ", label: "Canterbury" },
    { code: "OTA", label: "Otago" },
    { code: "WKO", label: "Waikato" },
    { code: "WGN", label: "Wellington" },
  ]),

  SA: alpha([
    { code: "ASR", label: "Asir" },
    { code: "ESH_SA", label: "Eastern Province" },
    { code: "MDN", label: "Madinah" },
    { code: "MKH", label: "Makkah" },
    { code: "RYD", label: "Riyadh" },
  ]),

  IL: alpha([
    { code: "CTR_IL", label: "Central District" },
    { code: "HFA", label: "Haifa District" },
    { code: "JM_IL", label: "Jerusalem District" },
    { code: "NTH_IL", label: "Northern District" },
    { code: "STH_IL", label: "Southern District" },
    { code: "TA", label: "Tel Aviv District" },
  ]),

  SE: alpha([
    { code: "SKN", label: "Skåne" },
    { code: "STK", label: "Stockholm" },
    { code: "VGT", label: "Västra Götaland" },
  ]),

  NO: alpha([
    { code: "OSL", label: "Oslo" },
    { code: "TRO_NO", label: "Trøndelag" },
    { code: "VKN", label: "Vestland" },
  ]),

  DK: alpha([
    { code: "CPH", label: "Capital Region" },
    { code: "MDJ", label: "Central Jutland" },
    { code: "SDK", label: "Southern Denmark" },
  ]),

  IE: alpha([
    { code: "CRK", label: "Cork" },
    { code: "DUB", label: "Dublin" },
    { code: "GAL_IE", label: "Galway" },
    { code: "LMK", label: "Limerick" },
  ]),

  SG: alpha([
    { code: "SG_C", label: "Central Region" },
    { code: "SG_E", label: "East Region" },
    { code: "SG_N", label: "North Region" },
    { code: "SG_NE", label: "North-East Region" },
    { code: "SG_W", label: "West Region" },
  ]),

  HK: alpha([
    { code: "HKI", label: "Hong Kong Island" },
    { code: "KLN", label: "Kowloon" },
    { code: "NTR", label: "New Territories" },
  ]),

  RU: alpha([
    { code: "KDA", label: "Krasnodar Krai" },
    { code: "MOW", label: "Moscow" },
    { code: "MOS", label: "Moscow Oblast" },
    { code: "NVS", label: "Novosibirsk Oblast" },
    { code: "SPE", label: "Saint Petersburg" },
    { code: "SVE", label: "Sverdlovsk Oblast" },
    { code: "TAT", label: "Tatarstan" },
  ]),

  PK: alpha([
    { code: "BA_PK", label: "Balochistan" },
    { code: "ICT", label: "Islamabad Capital Territory" },
    { code: "KP_PK", label: "Khyber Pakhtunkhwa" },
    { code: "PB_PK", label: "Punjab" },
    { code: "SD_PK", label: "Sindh" },
  ]),

  BD: alpha([
    { code: "BAR", label: "Barisal" },
    { code: "CHT", label: "Chittagong" },
    { code: "DHK", label: "Dhaka" },
    { code: "KHU", label: "Khulna" },
    { code: "RAJ_BD", label: "Rajshahi" },
    { code: "SYL", label: "Sylhet" },
  ]),

  EG: alpha([
    { code: "ALX", label: "Alexandria" },
    { code: "CAI", label: "Cairo" },
    { code: "GZ_EG", label: "Giza" },
    { code: "LUX", label: "Luxor" },
  ]),

  KE: alpha([
    { code: "CST_KE", label: "Coast" },
    { code: "CEN_KE", label: "Central" },
    { code: "NRB", label: "Nairobi" },
    { code: "RVP", label: "Rift Valley" },
  ]),

  GH: alpha([
    { code: "ASH", label: "Ashanti" },
    { code: "GAR", label: "Greater Accra" },
  ]),

  QA: alpha([
    { code: "DOH", label: "Doha" },
    { code: "RYN", label: "Al Rayyan" },
  ]),

  KW: alpha([
    { code: "AHM", label: "Ahmadi" },
    { code: "KWT", label: "Kuwait City" },
  ]),

  AT: alpha([
    { code: "BGL", label: "Burgenland" },
    { code: "KTN", label: "Carinthia" },
    { code: "NOE", label: "Lower Austria" },
    { code: "SBG", label: "Salzburg" },
    { code: "STM", label: "Styria" },
    { code: "TIR", label: "Tyrol" },
    { code: "OOE", label: "Upper Austria" },
    { code: "VBG", label: "Vorarlberg" },
    { code: "WIE", label: "Vienna" },
  ]),

  PT: alpha([
    { code: "AZO", label: "Azores" },
    { code: "FAR_PT", label: "Faro" },
    { code: "LIS", label: "Lisbon" },
    { code: "MAD_PT", label: "Madeira" },
    { code: "PRT", label: "Porto" },
  ]),

  GR: alpha([
    { code: "ATT", label: "Attica" },
    { code: "CMC", label: "Central Macedonia" },
    { code: "CRE", label: "Crete" },
    { code: "THS", label: "Thessaly" },
  ]),

  RO: alpha([
    { code: "BUC", label: "Bucharest" },
    { code: "CLJ", label: "Cluj" },
    { code: "CON_RO", label: "Constanța" },
    { code: "TIM", label: "Timiș" },
  ]),

  HU: alpha([
    { code: "BUD", label: "Budapest" },
    { code: "PES", label: "Pest" },
  ]),

  CZ: alpha([
    { code: "JMK", label: "South Moravian" },
    { code: "PHA", label: "Prague" },
  ]),

  TH: alpha([
    { code: "BKK", label: "Bangkok" },
    { code: "CNX", label: "Chiang Mai" },
    { code: "PKT", label: "Phuket" },
  ]),

  MY: alpha([
    { code: "JHR", label: "Johor" },
    { code: "KUL", label: "Kuala Lumpur" },
    { code: "PNG", label: "Penang" },
    { code: "SBH", label: "Sabah" },
    { code: "SRW", label: "Sarawak" },
    { code: "SGR", label: "Selangor" },
  ]),

  ID: alpha([
    { code: "BA_ID", label: "Bali" },
    { code: "JB", label: "East Java" },
    { code: "JK", label: "Jakarta" },
    { code: "JT", label: "Central Java" },
    { code: "JI", label: "West Java" },
  ]),

  VN: alpha([
    { code: "DAN", label: "Da Nang" },
    { code: "HAN", label: "Hanoi" },
    { code: "HCM", label: "Ho Chi Minh City" },
  ]),

  UA: alpha([
    { code: "KBP", label: "Kyiv" },
    { code: "LWO", label: "Lviv" },
    { code: "ODS", label: "Odesa" },
  ]),

  PE: alpha([
    { code: "ARE_PE", label: "Arequipa" },
    { code: "CUS", label: "Cusco" },
    { code: "LIM", label: "Lima" },
  ]),

  CL: alpha([
    { code: "BIO", label: "Biobío" },
    { code: "RM", label: "Santiago Metropolitan" },
    { code: "VAP", label: "Valparaíso" },
  ]),

  CR: alpha([
    { code: "SJ_CR", label: "San José" },
  ]),

  PA: alpha([
    { code: "PAN", label: "Panamá" },
  ]),

  JM: alpha([
    { code: "KNG", label: "Kingston" },
    { code: "SAN_JM", label: "Saint Andrew" },
  ]),

  TT: alpha([
    { code: "POS", label: "Port of Spain" },
    { code: "SFD", label: "San Fernando" },
  ]),

  FI: alpha([
    { code: "HEL", label: "Helsinki-Uusimaa" },
    { code: "PIR", label: "Pirkanmaa" },
  ]),

  BE: alpha([
    { code: "BRU", label: "Brussels" },
    { code: "FLA", label: "Flanders" },
    { code: "WAL", label: "Wallonia" },
  ]),

  TW: alpha([
    { code: "KHH", label: "Kaohsiung" },
    { code: "TNN", label: "Tainan" },
    { code: "TPE", label: "Taipei" },
  ]),

  VE: alpha([
    { code: "DC_VE", label: "Capital District" },
    { code: "ANZ", label: "Anzoátegui" },
    { code: "CAR", label: "Carabobo" },
    { code: "BOL_VE", label: "Bolívar" },
    { code: "MIR", label: "Miranda" },
    { code: "ZUL", label: "Zulia" },
  ]),

  BO: alpha([
    { code: "BEN", label: "Beni" },
    { code: "CBB", label: "Cochabamba" },
    { code: "LP_BO", label: "La Paz" },
    { code: "OR_BO", label: "Oruro" },
    { code: "POT", label: "Potosí" },
    { code: "SCZ", label: "Santa Cruz" },
    { code: "TJA", label: "Tarija" },
  ]),

  EC: alpha([
    { code: "AZU", label: "Azuay" },
    { code: "ELO", label: "El Oro" },
    { code: "GUA_EC", label: "Guayas" },
    { code: "IMB", label: "Imbabura" },
    { code: "MAN_EC", label: "Manabí" },
    { code: "PIC", label: "Pichincha" },
    { code: "TUN", label: "Tungurahua" },
  ]),

  PY: alpha([
    { code: "APA", label: "Alto Paraná" },
    { code: "ASU", label: "Asunción" },
    { code: "CEN_PY", label: "Central" },
    { code: "COR_PY", label: "Cordillera" },
    { code: "ITA", label: "Itapúa" },
    { code: "MIS_PY", label: "Misiones" },
  ]),

  UY: alpha([
    { code: "CAN_UY", label: "Canelones" },
    { code: "COL_UY", label: "Colonia" },
    { code: "MAL_UY", label: "Maldonado" },
    { code: "MON_UY", label: "Montevideo" },
    { code: "SJO_UY", label: "San José" },
  ]),

  GT: alpha([
    { code: "ESC", label: "Escuintla" },
    { code: "GUA_GT", label: "Guatemala" },
    { code: "IZA", label: "Izabal" },
    { code: "QUE_GT", label: "Quetzaltenango" },
    { code: "SAC", label: "Sacatepéquez" },
  ]),

  HN: alpha([
    { code: "CHO", label: "Choluteca" },
    { code: "COR_HN", label: "Cortés" },
    { code: "FM_HN", label: "Francisco Morazán" },
    { code: "OLN", label: "Olancho" },
    { code: "YOR", label: "Yoro" },
  ]),

  SV: alpha([
    { code: "LIB", label: "La Libertad" },
    { code: "SAM", label: "San Miguel" },
    { code: "SAN_SV", label: "Santa Ana" },
    { code: "SON_SV", label: "Sonsonate" },
    { code: "SS_SV", label: "San Salvador" },
  ]),

  NI: alpha([
    { code: "CHI_NI", label: "Chinandega" },
    { code: "GRA", label: "Granada" },
    { code: "LEO", label: "León" },
    { code: "MAN_NI", label: "Managua" },
  ]),

  CU: alpha([
    { code: "CMT", label: "Camagüey" },
    { code: "HAB", label: "Havana" },
    { code: "HOL", label: "Holguín" },
    { code: "SCU", label: "Santiago de Cuba" },
    { code: "VCL", label: "Villa Clara" },
  ]),

  DO: alpha([
    { code: "DIS_DO", label: "Distrito Nacional" },
    { code: "LAR_DO", label: "La Romana" },
    { code: "SDO", label: "Santo Domingo" },
    { code: "SPM", label: "San Pedro de Macorís" },
    { code: "STO_DO", label: "Santiago" },
  ]),

  HT: alpha([
    { code: "ARB", label: "Artibonite" },
    { code: "CEN_HT", label: "Centre" },
    { code: "NRD", label: "Nord" },
    { code: "OUE", label: "Ouest" },
  ]),

  PR: alpha([
    { code: "BAY_PR", label: "Bayamón" },
    { code: "CAG", label: "Caguas" },
    { code: "CAR_PR", label: "Carolina" },
    { code: "PON_PR", label: "Ponce" },
    { code: "SJN", label: "San Juan" },
  ]),

  ET: alpha([
    { code: "ADD", label: "Addis Ababa" },
    { code: "AMH", label: "Amhara" },
    { code: "DIR_ET", label: "Dire Dawa" },
    { code: "ORM", label: "Oromia" },
    { code: "SNK", label: "SNNPR" },
    { code: "SOM_ET", label: "Somali" },
    { code: "TGR", label: "Tigray" },
  ]),

  TZ: alpha([
    { code: "ARU", label: "Arusha" },
    { code: "DAR", label: "Dar es Salaam" },
    { code: "DOD", label: "Dodoma" },
    { code: "MBY", label: "Mbeya" },
    { code: "MOR_TZ", label: "Morogoro" },
    { code: "MWA", label: "Mwanza" },
    { code: "TAN_TZ", label: "Tanga" },
    { code: "ZAN", label: "Zanzibar" },
  ]),

  MA: alpha([
    { code: "CAS", label: "Casablanca-Settat" },
    { code: "FES", label: "Fès-Meknès" },
    { code: "MAR_MA", label: "Marrakesh-Safi" },
    { code: "ORI", label: "Oriental" },
    { code: "RBC", label: "Rabat-Salé-Kénitra" },
    { code: "SOU_MA", label: "Souss-Massa" },
    { code: "TAN_MA", label: "Tanger-Tétouan-Al Hoceïma" },
  ]),

  DZ: alpha([
    { code: "ALG", label: "Algiers" },
    { code: "ANN_DZ", label: "Annaba" },
    { code: "BLI", label: "Blida" },
    { code: "CON_DZ", label: "Constantine" },
    { code: "ORA", label: "Oran" },
    { code: "SET_DZ", label: "Sétif" },
    { code: "TLE", label: "Tlemcen" },
  ]),

  AO: alpha([
    { code: "BIE", label: "Bié" },
    { code: "HUA", label: "Huambo" },
    { code: "HUI", label: "Huíla" },
    { code: "LNO", label: "Lunda Norte" },
    { code: "LUA_AO", label: "Luanda" },
    { code: "MAL_AO", label: "Malanje" },
  ]),

  CM: alpha([
    { code: "ADA", label: "Adamaoua" },
    { code: "CEN_CM", label: "Centre" },
    { code: "LIT_CM", label: "Littoral" },
    { code: "NOR_CM", label: "North West" },
    { code: "OUE_CM", label: "Ouest" },
    { code: "SOR_CM", label: "South West" },
  ]),

  MZ: alpha([
    { code: "GZA", label: "Gaza" },
    { code: "INH", label: "Inhambane" },
    { code: "MAP_MZ", label: "Maputo" },
    { code: "NAM_MZ", label: "Nampula" },
    { code: "SOF_MZ", label: "Sofala" },
    { code: "ZAM", label: "Zambézia" },
  ]),

  ZW: alpha([
    { code: "BUL_ZW", label: "Bulawayo" },
    { code: "HAR_ZW", label: "Harare" },
    { code: "MAN_ZW", label: "Manicaland" },
    { code: "MAS_ZW", label: "Mashonaland East" },
    { code: "MID_ZW", label: "Midlands" },
  ]),

  ZM: alpha([
    { code: "COP", label: "Copperbelt" },
    { code: "EAS_ZM", label: "Eastern" },
    { code: "LUA_ZM", label: "Luapula" },
    { code: "LUS_ZM", label: "Lusaka" },
    { code: "SHE_ZM", label: "Southern" },
  ]),

  UG: alpha([
    { code: "CEN_UG", label: "Central" },
    { code: "EAS_UG", label: "Eastern" },
    { code: "KAM_UG", label: "Kampala" },
    { code: "NOR_UG", label: "Northern" },
    { code: "WES_UG", label: "Western" },
  ]),

  SN: alpha([
    { code: "DKR", label: "Dakar" },
    { code: "DIO", label: "Diourbel" },
    { code: "SEN_LO", label: "Saint-Louis" },
    { code: "THI", label: "Thiès" },
    { code: "ZIG", label: "Ziguinchor" },
  ]),

  CI: alpha([
    { code: "ABI", label: "Abidjan" },
    { code: "GOM_CI", label: "Gôh-Djiboua" },
    { code: "MEN_CI", label: "Montagnes" },
    { code: "VBR", label: "Vallée du Bandama" },
  ]),

  RW: alpha([
    { code: "EAS_RW", label: "Eastern" },
    { code: "KIG", label: "Kigali" },
    { code: "NOR_RW", label: "Northern" },
    { code: "SOU_RW", label: "Southern" },
    { code: "WES_RW", label: "Western" },
  ]),

  LY: alpha([
    { code: "BEN_LY", label: "Benghazi" },
    { code: "MIS_LY", label: "Misrata" },
    { code: "TRI_LY", label: "Tripoli" },
  ]),

  TN: alpha([
    { code: "KAI_TN", label: "Kairouan" },
    { code: "SFA", label: "Sfax" },
    { code: "SOU_TN", label: "Sousse" },
    { code: "TUN_TN", label: "Tunis" },
  ]),

  SD: alpha([
    { code: "GAD", label: "Gedaref" },
    { code: "KAS_SD", label: "Kassala" },
    { code: "KHT_SD", label: "Khartoum" },
    { code: "POR_SD", label: "Port Sudan" },
  ]),

  CD: alpha([
    { code: "GOB", label: "Goma (North Kivu)" },
    { code: "KIN_CD", label: "Kinshasa" },
    { code: "KIS_CD", label: "Kisangani (Tshopo)" },
    { code: "LUB_CD", label: "Lubumbashi (Haut-Katanga)" },
    { code: "MBU", label: "Mbuji-Mayi (Kasai-Oriental)" },
  ]),

  CG: alpha([
    { code: "BRZ", label: "Brazzaville" },
    { code: "KIB", label: "Kouilou" },
    { code: "PLT_CG", label: "Pointe-Noire" },
  ]),

  NA: alpha([
    { code: "ERA_NA", label: "Erongo" },
    { code: "KHM_NA", label: "Khomas" },
    { code: "OSH_NA", label: "Oshana" },
  ]),

  BW: alpha([
    { code: "KGT", label: "Kgatleng" },
    { code: "NGW", label: "Ngwaketse" },
    { code: "SE_BW", label: "South-East" },
  ]),

  MW: alpha([
    { code: "BLA_MW", label: "Blantyre" },
    { code: "LIL_MW", label: "Lilongwe" },
    { code: "MZU_MW", label: "Mzuzu" },
  ]),

  ML: alpha([
    { code: "BKO", label: "Bamako" },
    { code: "KOU", label: "Koulikoro" },
    { code: "MOP", label: "Mopti" },
    { code: "SIK_ML", label: "Sikasso" },
  ]),

  BF: alpha([
    { code: "CEN_BF", label: "Centre" },
    { code: "HBS", label: "Hauts-Bassins" },
    { code: "PLT_BF", label: "Plateau-Central" },
  ]),

  NE: alpha([
    { code: "MAR_NE", label: "Maradi" },
    { code: "NIA_NE", label: "Niamey" },
    { code: "TAH", label: "Tahoua" },
    { code: "ZIN_NE", label: "Zinder" },
  ]),

  IQ: alpha([
    { code: "ANB", label: "Anbar" },
    { code: "BGD_IQ", label: "Baghdad" },
    { code: "BAS_IQ", label: "Basra" },
    { code: "EBL", label: "Erbil" },
    { code: "KRB", label: "Karbala" },
    { code: "NIN", label: "Nineveh" },
    { code: "NJF", label: "Najaf" },
    { code: "SUL_IQ", label: "Sulaymaniyah" },
  ]),

  JO: alpha([
    { code: "AMM_JO", label: "Amman" },
    { code: "AQB", label: "Aqaba" },
    { code: "IRL", label: "Irbid" },
    { code: "ZRQ", label: "Zarqa" },
  ]),

  LB: alpha([
    { code: "BEI", label: "Beirut" },
    { code: "BEK", label: "Bekaa" },
    { code: "MTN", label: "Mount Lebanon" },
    { code: "NOR_LB", label: "North Lebanon" },
    { code: "SOU_LB", label: "South Lebanon" },
  ]),

  OM: alpha([
    { code: "BAT_NO", label: "Batinah North" },
    { code: "BAT_SO", label: "Batinah South" },
    { code: "DHO", label: "Dhofar" },
    { code: "MSQ", label: "Muscat" },
  ]),

  YE: alpha([
    { code: "ADE_YE", label: "Aden" },
    { code: "HOD", label: "Hudaydah" },
    { code: "IBB", label: "Ibb" },
    { code: "SAN_YE", label: "Sana'a" },
    { code: "TAI", label: "Taiz" },
  ]),

  IR: alpha([
    { code: "AZB_E", label: "East Azerbaijan" },
    { code: "FAR_IR", label: "Fars" },
    { code: "GIL", label: "Gilan" },
    { code: "ISF", label: "Isfahan" },
    { code: "KER_IR", label: "Kerman" },
    { code: "KHO", label: "Khorasan Razavi" },
    { code: "KHZ", label: "Khuzestan" },
    { code: "MAZ", label: "Mazandaran" },
    { code: "TEH", label: "Tehran" },
  ]),

  BH: alpha([
    { code: "CAP_BH", label: "Capital" },
    { code: "CEN_BH", label: "Central" },
    { code: "MUH", label: "Muharraq" },
    { code: "NOR_BH", label: "Northern" },
    { code: "SOU_BH", label: "Southern" },
  ]),

  PS: alpha([
    { code: "GAZ", label: "Gaza Strip" },
    { code: "WBK", label: "West Bank" },
  ]),

  SY: alpha([
    { code: "ALE", label: "Aleppo" },
    { code: "DAM_SY", label: "Damascus" },
    { code: "HMA", label: "Hama" },
    { code: "HMS", label: "Homs" },
    { code: "LAT", label: "Latakia" },
  ]),

  KZ: alpha([
    { code: "AKT_KZ", label: "Aktobe" },
    { code: "ALA_KZ", label: "Almaty" },
    { code: "AST_KZ", label: "Astana" },
    { code: "KAR_KZ", label: "Karaganda" },
    { code: "SHM_KZ", label: "Shymkent" },
  ]),

  UZ: alpha([
    { code: "AND_UZ", label: "Andijan" },
    { code: "BUK_UZ", label: "Bukhara" },
    { code: "FAR_UZ", label: "Fergana" },
    { code: "NAM_UZ", label: "Namangan" },
    { code: "SAM_UZ", label: "Samarkand" },
    { code: "TAS_UZ", label: "Tashkent" },
  ]),

  AZ: alpha([
    { code: "BAK_AZ", label: "Baku" },
    { code: "GAN_AZ", label: "Ganja" },
    { code: "SUM_AZ", label: "Sumqayit" },
  ]),

  AM: alpha([
    { code: "ARA_AM", label: "Ararat" },
    { code: "GEG_AM", label: "Gegharkunik" },
    { code: "SHI_AM", label: "Shirak" },
    { code: "YER_AM", label: "Yerevan" },
  ]),

  GE: alpha([
    { code: "AJA", label: "Adjara" },
    { code: "IMR_GE", label: "Imereti" },
    { code: "KVT", label: "Kvemo Kartli" },
    { code: "TBS", label: "Tbilisi" },
  ]),

  MM: alpha([
    { code: "AYE", label: "Ayeyarwady" },
    { code: "BAG_MM", label: "Bago" },
    { code: "MDL", label: "Mandalay" },
    { code: "NPT", label: "Naypyidaw" },
    { code: "SAG_MM", label: "Sagaing" },
    { code: "YGN", label: "Yangon" },
  ]),

  NP: alpha([
    { code: "BAG_NP", label: "Bagmati" },
    { code: "GAB_NP", label: "Gandaki" },
    { code: "KAR_NP", label: "Karnali" },
    { code: "KOS_NP", label: "Koshi" },
    { code: "LUM_NP", label: "Lumbini" },
    { code: "MAD_NP", label: "Madhesh" },
    { code: "SUD_NP", label: "Sudurpashchim" },
  ]),

  LK: alpha([
    { code: "CEN_LK", label: "Central Province" },
    { code: "EAS_LK", label: "Eastern Province" },
    { code: "NOR_LK", label: "Northern Province" },
    { code: "NWE_LK", label: "North Western Province" },
    { code: "SOU_LK", label: "Southern Province" },
    { code: "WES_LK", label: "Western Province" },
  ]),

  AF: alpha([
    { code: "BAL_AF", label: "Balkh" },
    { code: "HER_AF", label: "Herat" },
    { code: "KBL_AF", label: "Kabul" },
    { code: "KDH", label: "Kandahar" },
    { code: "NNR", label: "Nangarhar" },
  ]),

  KH: alpha([
    { code: "BTB", label: "Battambang" },
    { code: "KPT_KH", label: "Kampot" },
    { code: "PNH", label: "Phnom Penh" },
    { code: "SRP_KH", label: "Siem Reap" },
  ]),

  LA: alpha([
    { code: "CHM", label: "Champasak" },
    { code: "LPB", label: "Luang Prabang" },
    { code: "SAV_LA", label: "Savannakhet" },
    { code: "VTE", label: "Vientiane" },
  ]),

  MN: alpha([
    { code: "DRK", label: "Darkhan-Uul" },
    { code: "ORK", label: "Orkhon" },
    { code: "ULN", label: "Ulaanbaatar" },
  ]),

  KG: alpha([
    { code: "BSH_KG", label: "Bishkek" },
    { code: "JAL_KG", label: "Jalal-Abad" },
    { code: "OSH_KG", label: "Osh" },
  ]),

  TJ: alpha([
    { code: "DUS_TJ", label: "Dushanbe" },
    { code: "KHT_TJ", label: "Khatlon" },
    { code: "SDA_TJ", label: "Sughd" },
  ]),

  SK: alpha([
    { code: "BAN_SK", label: "Banská Bystrica" },
    { code: "BRA_SK", label: "Bratislava" },
    { code: "KOS_SK", label: "Košice" },
    { code: "NIT_SK", label: "Nitra" },
    { code: "PRE_SK", label: "Prešov" },
    { code: "TRE_SK", label: "Trenčín" },
    { code: "TRN_SK", label: "Trnava" },
    { code: "ZIL_SK", label: "Žilina" },
  ]),

  SI: alpha([
    { code: "CEL_SI", label: "Celje" },
    { code: "KRA_SI", label: "Kranj" },
    { code: "LJU", label: "Ljubljana" },
    { code: "MBX", label: "Maribor" },
  ]),

  HR: alpha([
    { code: "OSI", label: "Osijek-Baranja" },
    { code: "RIJ", label: "Primorje-Gorski Kotar" },
    { code: "SPL", label: "Split-Dalmatia" },
    { code: "ZAD", label: "Zadar" },
    { code: "ZAG_HR", label: "Zagreb" },
  ]),

  RS: alpha([
    { code: "BGD_RS", label: "Belgrade" },
    { code: "NIS_RS", label: "Southern and Eastern Serbia" },
    { code: "SNI", label: "Šumadija and Western Serbia" },
    { code: "VOJ", label: "Vojvodina" },
  ]),

  BG: alpha([
    { code: "BUR_BG", label: "Burgas" },
    { code: "PLV", label: "Plovdiv" },
    { code: "SOF_BG", label: "Sofia" },
    { code: "STZ", label: "Stara Zagora" },
    { code: "VAR_BG", label: "Varna" },
  ]),

  EE: alpha([
    { code: "HAR_EE", label: "Harju" },
    { code: "IDA_EE", label: "Ida-Viru" },
    { code: "TAR_EE", label: "Tartu" },
  ]),

  LV: alpha([
    { code: "DAG_LV", label: "Daugavpils" },
    { code: "JEL_LV", label: "Jelgava" },
    { code: "RGA", label: "Riga" },
  ]),

  LT: alpha([
    { code: "KAU_LT", label: "Kaunas" },
    { code: "KLJ", label: "Klaipėda" },
    { code: "SIA_LT", label: "Šiauliai" },
    { code: "VIL_LT", label: "Vilnius" },
  ]),

  IS: alpha([
    { code: "CAP_IS", label: "Capital Region" },
    { code: "SOU_IS", label: "Southern Region" },
    { code: "WES_IS", label: "Western Region" },
  ]),

  AL: alpha([
    { code: "DUR_AL", label: "Durrës" },
    { code: "SHK_AL", label: "Shkodër" },
    { code: "TIR_AL", label: "Tirana" },
    { code: "VLO_AL", label: "Vlorë" },
  ]),

  BA: alpha([
    { code: "FBH", label: "Federation of BiH" },
    { code: "SAR_BA", label: "Sarajevo" },
    { code: "SRP_BA", label: "Republika Srpska" },
  ]),

  MK: alpha([
    { code: "PHN_MK", label: "Pelagonia" },
    { code: "SKP", label: "Skopje" },
    { code: "VRD_MK", label: "Vardar" },
  ]),

  ME: alpha([
    { code: "BDV", label: "Budva" },
    { code: "NKS", label: "Nikšić" },
    { code: "POD", label: "Podgorica" },
  ]),

  BY: alpha([
    { code: "BRS_BY", label: "Brest" },
    { code: "GOM_BY", label: "Gomel" },
    { code: "GRD_BY", label: "Grodno" },
    { code: "MIN_BY", label: "Minsk" },
    { code: "MOG_BY", label: "Mogilev" },
    { code: "VIT_BY", label: "Vitebsk" },
  ]),

  MD: alpha([
    { code: "BAL_MD", label: "Bălți" },
    { code: "CHI_MD", label: "Chișinău" },
    { code: "TGH_MD", label: "Tiraspol" },
  ]),

  LU: alpha([
    { code: "DIF_LU", label: "Differdange" },
    { code: "ESH_LU", label: "Esch-sur-Alzette" },
    { code: "LUX_C", label: "Luxembourg City" },
  ]),

  MT: alpha([
    { code: "BKR_MT", label: "Birkirkara" },
    { code: "SLM_MT", label: "Sliema" },
    { code: "VAL_MT", label: "Valletta" },
  ]),
};

const CITIES_BY_STATE: Record<string, string[]> = {
  Alabama: ["Birmingham", "Dothan", "Hoover", "Huntsville", "Mobile", "Montgomery", "Tuscaloosa"],
  Alaska: ["Anchorage", "Fairbanks", "Juneau", "Ketchikan", "Kodiak", "Sitka", "Wasilla"],
  Arizona: ["Chandler", "Gilbert", "Glendale", "Mesa", "Peoria", "Phoenix", "Scottsdale", "Surprise", "Tempe", "Tucson"],
  Arkansas: ["Conway", "Fayetteville", "Fort Smith", "Jonesboro", "Little Rock", "North Little Rock", "Rogers", "Springdale"],
  California: ["Anaheim", "Bakersfield", "Chula Vista", "Fontana", "Fremont", "Fresno", "Irvine", "Long Beach", "Los Angeles", "Modesto", "Oakland", "Oxnard", "Riverside", "Sacramento", "San Bernardino", "San Diego", "San Francisco", "San Jose", "Santa Ana", "Stockton"],
  Colorado: ["Arvada", "Aurora", "Boulder", "Colorado Springs", "Denver", "Fort Collins", "Lakewood", "Pueblo", "Thornton", "Westminster"],
  Connecticut: ["Bridgeport", "Danbury", "Greenwich", "Hartford", "New Britain", "New Haven", "Norwalk", "Stamford", "Waterbury"],
  Delaware: ["Dover", "Georgetown", "Middletown", "Milford", "Newark", "Seaford", "Smyrna", "Wilmington"],
  "District of Columbia": ["Washington"],
  Florida: ["Cape Coral", "Coral Springs", "Davie", "Fort Lauderdale", "Gainesville", "Hialeah", "Hollywood", "Jacksonville", "Lakeland", "Miami", "Miami Gardens", "Miramar", "Orlando", "Pembroke Pines", "Pompano Beach", "Port St. Lucie", "St. Petersburg", "Tallahassee", "Tampa", "West Palm Beach"],
  Georgia: ["Albany", "Athens", "Atlanta", "Augusta", "Columbus", "Johns Creek", "Macon", "Roswell", "Sandy Springs", "Savannah"],
  Hawaii: ["Hilo", "Honolulu", "Kahului", "Kailua", "Kaneohe", "Mililani Town", "Pearl City", "Waipahu"],
  Idaho: ["Boise", "Caldwell", "Coeur d'Alene", "Idaho Falls", "Meridian", "Nampa", "Pocatello", "Twin Falls"],
  Illinois: ["Aurora", "Champaign", "Chicago", "Elgin", "Joliet", "Naperville", "Peoria", "Rockford", "Springfield", "Waukegan"],
  Indiana: ["Bloomington", "Carmel", "Evansville", "Fishers", "Fort Wayne", "Gary", "Hammond", "Indianapolis", "Lafayette", "South Bend"],
  Iowa: ["Ames", "Cedar Rapids", "Council Bluffs", "Davenport", "Des Moines", "Iowa City", "Sioux City", "Waterloo"],
  Kansas: ["Kansas City", "Lawrence", "Manhattan", "Olathe", "Overland Park", "Shawnee", "Topeka", "Wichita"],
  Kentucky: ["Bowling Green", "Covington", "Florence", "Hopkinsville", "Lexington", "Louisville", "Owensboro", "Richmond"],
  Louisiana: ["Baton Rouge", "Bossier City", "Kenner", "Lafayette", "Lake Charles", "Metairie", "Monroe", "New Orleans", "Shreveport"],
  Maine: ["Auburn", "Augusta", "Bangor", "Biddeford", "Lewiston", "Portland", "Sanford", "South Portland"],
  Maryland: ["Annapolis", "Baltimore", "Bowie", "College Park", "Frederick", "Gaithersburg", "Hagerstown", "Rockville", "Salisbury"],
  Massachusetts: ["Boston", "Brockton", "Cambridge", "Fall River", "Lowell", "Lynn", "New Bedford", "Quincy", "Springfield", "Worcester"],
  Michigan: ["Ann Arbor", "Clinton Township", "Dearborn", "Detroit", "Flint", "Grand Rapids", "Lansing", "Livonia", "Sterling Heights", "Warren"],
  Minnesota: ["Bloomington", "Brooklyn Park", "Duluth", "Minneapolis", "Plymouth", "Rochester", "Saint Cloud", "Saint Paul"],
  Mississippi: ["Biloxi", "Gulfport", "Hattiesburg", "Jackson", "Meridian", "Olive Branch", "Southaven", "Tupelo"],
  Missouri: ["Columbia", "Independence", "Kansas City", "Lee's Summit", "O'Fallon", "Saint Louis", "Springfield", "St. Joseph"],
  Montana: ["Billings", "Bozeman", "Butte", "Great Falls", "Havre", "Helena", "Kalispell", "Missoula"],
  Nebraska: ["Bellevue", "Fremont", "Grand Island", "Hastings", "Kearney", "Lincoln", "North Platte", "Omaha"],
  Nevada: ["Carson City", "Elko", "Fernley", "Henderson", "Las Vegas", "North Las Vegas", "Reno", "Sparks"],
  "New Hampshire": ["Concord", "Dover", "Hudson", "Manchester", "Merrimack", "Nashua", "Rochester", "Salem"],
  "New Jersey": ["Edison", "Elizabeth", "Jersey City", "Newark", "Paterson", "Toms River", "Trenton"],
  "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Roswell", "Santa Fe"],
  "New York": ["Albany", "Buffalo", "New York City", "Rochester", "Syracuse", "Yonkers"],
  "North Carolina": ["Charlotte", "Durham", "Fayetteville", "Greensboro", "Raleigh", "Winston-Salem"],
  "North Dakota": ["Bismarck", "Fargo", "Grand Forks", "Minot", "West Fargo"],
  Ohio: ["Akron", "Cincinnati", "Cleveland", "Columbus", "Dayton", "Toledo"],
  Oklahoma: ["Broken Arrow", "Lawton", "Norman", "Oklahoma City", "Tulsa"],
  Oregon: ["Bend", "Eugene", "Gresham", "Hillsboro", "Portland", "Salem"],
  Pennsylvania: ["Allentown", "Erie", "Harrisburg", "Philadelphia", "Pittsburgh", "Reading", "Scranton"],
  "Rhode Island": ["Cranston", "East Providence", "Pawtucket", "Providence", "Warwick"],
  "South Carolina": ["Charleston", "Columbia", "Greenville", "Mount Pleasant", "North Charleston"],
  "South Dakota": ["Aberdeen", "Brookings", "Rapid City", "Sioux Falls", "Watertown"],
  Tennessee: ["Chattanooga", "Clarksville", "Knoxville", "Memphis", "Nashville"],
  Texas: ["Arlington", "Austin", "Corpus Christi", "Dallas", "El Paso", "Fort Worth", "Houston", "Laredo", "Plano", "San Antonio"],
  Utah: ["Orem", "Provo", "Salt Lake City", "West Jordan", "West Valley City"],
  Vermont: ["Barre", "Burlington", "Montpelier", "Rutland", "South Burlington"],
  Virginia: ["Arlington", "Chesapeake", "Newport News", "Norfolk", "Richmond", "Virginia Beach"],
  Washington: ["Bellevue", "Kirkland", "Seattle", "Spokane", "Tacoma", "Vancouver"],
  "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  Wisconsin: ["Green Bay", "Kenosha", "Madison", "Milwaukee", "Racine"],
  Wyoming: ["Casper", "Cheyenne", "Gillette", "Laramie", "Rock Springs"],

  AB: ["Calgary", "Edmonton", "Lethbridge", "Medicine Hat", "Red Deer", "St. Albert"],
  BC: ["Abbotsford", "Burnaby", "Kelowna", "Richmond", "Surrey", "Vancouver", "Victoria"],
  MB: ["Brandon", "Steinbach", "Thompson", "Winnipeg"],
  NB: ["Fredericton", "Miramichi", "Moncton", "Saint John"],
  NL_CA: ["Corner Brook", "Gander", "Mount Pearl", "St. John's"],
  NS: ["Dartmouth", "Halifax", "Sydney", "Truro"],
  NT: ["Hay River", "Inuvik", "Yellowknife"],
  NU: ["Iqaluit", "Rankin Inlet"],
  ON: ["Brampton", "Hamilton", "Kitchener", "London", "Markham", "Mississauga", "Ottawa", "Toronto", "Vaughan", "Windsor"],
  PE: ["Charlottetown", "Stratford", "Summerside"],
  QC: ["Gatineau", "Laval", "Longueuil", "Montreal", "Quebec City", "Sherbrooke"],
  SK: ["Moose Jaw", "Prince Albert", "Regina", "Saskatoon"],
  YT: ["Dawson City", "Whitehorse"],

  ENG: ["Birmingham", "Bristol", "Leeds", "Leicester", "Liverpool", "London", "Manchester", "Newcastle", "Nottingham", "Sheffield"],
  SCT: ["Aberdeen", "Dundee", "Edinburgh", "Glasgow", "Inverness", "Stirling"],
  WLS: ["Bangor", "Cardiff", "Newport", "Swansea", "Wrexham"],
  NIR: ["Bangor", "Belfast", "Derry", "Lisburn", "Newry"],

  ACT: ["Belconnen", "Canberra", "Tuggeranong"],
  NSW: ["Central Coast", "Coffs Harbour", "Newcastle", "Sydney", "Wollongong"],
  NT_AU: ["Alice Springs", "Darwin", "Katherine", "Palmerston"],
  QLD: ["Brisbane", "Cairns", "Gold Coast", "Sunshine Coast", "Townsville"],
  SA_AU: ["Adelaide", "Mount Gambier", "Murray Bridge", "Whyalla"],
  TAS: ["Burnie", "Devonport", "Hobart", "Launceston"],
  VIC: ["Ballarat", "Bendigo", "Geelong", "Melbourne", "Shepparton"],
  WA: ["Bunbury", "Fremantle", "Joondalup", "Mandurah", "Perth"],

  BW: ["Freiburg", "Heidelberg", "Karlsruhe", "Mannheim", "Stuttgart"],
  BY: ["Augsburg", "Munich", "Nuremberg", "Regensburg", "Würzburg"],
  BE_DE: ["Berlin"],
  BB: ["Brandenburg an der Havel", "Cottbus", "Potsdam"],
  HB: ["Bremen", "Bremerhaven"],
  HH: ["Hamburg"],
  HE: ["Darmstadt", "Frankfurt", "Kassel", "Offenbach", "Wiesbaden"],
  MV: ["Neubrandenburg", "Rostock", "Schwerin"],
  NI_DE: ["Braunschweig", "Göttingen", "Hanover", "Oldenburg", "Osnabrück"],
  NW: ["Bonn", "Cologne", "Dortmund", "Duisburg", "Düsseldorf", "Essen", "Münster"],
  RP: ["Koblenz", "Ludwigshafen", "Mainz", "Trier"],
  SL_DE: ["Saarbrücken"],
  SN_DE: ["Chemnitz", "Dresden", "Leipzig"],
  ST_DE: ["Halle", "Magdeburg"],
  SH: ["Flensburg", "Kiel", "Lübeck"],
  TH_DE: ["Erfurt", "Jena", "Weimar"],

  ARA: ["Clermont-Ferrand", "Grenoble", "Lyon", "Saint-Étienne"],
  BFC: ["Besançon", "Dijon"],
  BRE: ["Brest", "Quimper", "Rennes", "Saint-Malo"],
  CVL: ["Blois", "Orléans", "Tours"],
  COR: ["Ajaccio", "Bastia"],
  GES: ["Metz", "Mulhouse", "Nancy", "Reims", "Strasbourg"],
  HDF: ["Amiens", "Dunkirk", "Lille", "Roubaix"],
  IDF: ["Boulogne-Billancourt", "Nanterre", "Paris", "Saint-Denis", "Versailles"],
  NOR: ["Caen", "Le Havre", "Rouen"],
  NAQ: ["Bordeaux", "La Rochelle", "Limoges", "Poitiers"],
  OCC: ["Montpellier", "Nîmes", "Perpignan", "Toulouse"],
  PAC: ["Aix-en-Provence", "Cannes", "Marseille", "Nice", "Toulon"],
  PDL: ["Angers", "Le Mans", "Nantes"],

  AP: ["Guntur", "Nellore", "Tirupati", "Vijayawada", "Visakhapatnam"],
  AR_IN: ["Itanagar"],
  AS: ["Dibrugarh", "Guwahati", "Silchar"],
  BR_IN: ["Gaya", "Muzaffarpur", "Patna"],
  CG_IN: ["Bhilai", "Bilaspur", "Raipur"],
  DL: ["Faridabad", "Ghaziabad", "Gurgaon", "New Delhi", "Noida"],
  GA_IN: ["Margao", "Panaji", "Vasco da Gama"],
  GJ: ["Ahmedabad", "Gandhinagar", "Rajkot", "Surat", "Vadodara"],
  HR_IN: ["Ambala", "Faridabad", "Gurgaon", "Karnal", "Panipat"],
  HP: ["Dharamshala", "Shimla"],
  JH: ["Dhanbad", "Jamshedpur", "Ranchi"],
  KA: ["Bangalore", "Belgaum", "Hubli", "Mangalore", "Mysore"],
  KL: ["Kochi", "Kozhikode", "Thiruvananthapuram", "Thrissur"],
  MP_IN: ["Bhopal", "Gwalior", "Indore", "Jabalpur"],
  MH: ["Mumbai", "Nagpur", "Nashik", "Navi Mumbai", "Pune", "Thane"],
  MN_IN: ["Imphal"],
  ML_IN: ["Shillong"],
  MZ_IN: ["Aizawl"],
  NL_IN: ["Kohima"],
  OD: ["Bhubaneswar", "Cuttack", "Rourkela"],
  PB: ["Amritsar", "Jalandhar", "Ludhiana", "Patiala"],
  RJ: ["Ajmer", "Bikaner", "Jaipur", "Jodhpur", "Kota", "Udaipur"],
  SK_IN: ["Gangtok"],
  TN: ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli"],
  TS: ["Hyderabad", "Karimnagar", "Nizamabad", "Warangal"],
  TR_IN: ["Agartala"],
  UP: ["Agra", "Allahabad", "Kanpur", "Lucknow", "Meerut", "Varanasi"],
  UK_IN: ["Dehradun", "Haridwar"],
  WB: ["Asansol", "Durgapur", "Howrah", "Kolkata", "Siliguri"],

  JP13: ["Chiyoda", "Minato", "Shibuya", "Shinjuku", "Tokyo"],
  JP27: ["Higashiosaka", "Osaka", "Sakai"],
  JP23: ["Nagoya", "Okazaki", "Toyota"],
  JP14: ["Kawasaki", "Sagamihara", "Yokohama"],
  JP11: ["Kawagoe", "Kawaguchi", "Saitama"],
  JP12: ["Chiba", "Funabashi", "Kashiwa"],
  JP01: ["Asahikawa", "Hakodate", "Sapporo"],
  JP40: ["Fukuoka", "Kitakyushu"],
  JP26: ["Kyoto"],
  JP28: ["Himeji", "Kobe", "Nishinomiya"],

  AGU: ["Aguascalientes"],
  BCN: ["Ensenada", "Mexicali", "Tijuana"],
  CMX: ["Mexico City"],
  JAL: ["Guadalajara", "Tlaquepaque", "Zapopan"],
  NLE: ["Monterrey", "San Nicolás", "San Pedro Garza García"],
  GUA: ["Celaya", "Irapuato", "León"],
  PUE: ["Puebla", "Tehuacán"],
  QUE: ["Querétaro"],
  YUC: ["Mérida"],

  SP: ["Campinas", "Guarulhos", "Ribeirão Preto", "Santos", "São Paulo"],
  RJ_BR: ["Niterói", "Petrópolis", "Rio de Janeiro"],
  MG_BR: ["Belo Horizonte", "Juiz de Fora", "Uberlândia"],
  BA: ["Feira de Santana", "Salvador"],
  RS: ["Caxias do Sul", "Pelotas", "Porto Alegre"],
  PR_BR: ["Curitiba", "Londrina", "Maringá"],
  PE_BR: ["Jaboatão", "Olinda", "Recife"],
  CE: ["Fortaleza", "Juazeiro do Norte"],
  DF_BR: ["Brasília"],
  SC_BR: ["Blumenau", "Florianópolis", "Joinville"],
  GO: ["Aparecida de Goiânia", "Goiânia"],

  LAZ: ["Frosinone", "Latina", "Rome"],
  LOM: ["Bergamo", "Brescia", "Milan", "Monza"],
  CAM_IT: ["Caserta", "Naples", "Salerno"],
  SIC: ["Catania", "Messina", "Palermo"],
  VEN: ["Padua", "Venice", "Verona", "Vicenza"],
  PIE: ["Alessandria", "Novara", "Turin"],
  EMR: ["Bologna", "Modena", "Parma", "Rimini"],
  TOS: ["Florence", "Livorno", "Pisa", "Siena"],

  MD_ES: ["Alcalá de Henares", "Getafe", "Madrid"],
  CT: ["Barcelona", "Girona", "Tarragona"],
  AN_ES: ["Córdoba", "Granada", "Málaga", "Seville"],
  VC_ES: ["Alicante", "Castellón", "Valencia"],

  NH: ["Amsterdam", "Haarlem", "Hilversum"],
  ZH_NL: ["Delft", "Leiden", "Rotterdam", "The Hague"],
  NB_NL: ["Breda", "Eindhoven", "Tilburg"],
  GE_NL: ["Apeldoorn", "Arnhem", "Nijmegen"],
  UT_NL: ["Amersfoort", "Utrecht"],

  ZH_CH: ["Winterthur", "Zürich"],
  BE_CH: ["Bern", "Biel", "Thun"],
  VD: ["Lausanne", "Montreux", "Nyon"],
  GE_CH: ["Geneva"],
  LU_CH: ["Lucerne"],
  BS_CH: ["Basel"],
  TI: ["Bellinzona", "Lugano"],

  AUH: ["Abu Dhabi", "Al Ain"],
  DXB: ["Dubai", "Jebel Ali"],
  SHJ: ["Sharjah"],
  RAK: ["Ras al-Khaimah"],
  AJM: ["Ajman"],
  FUJ: ["Fujairah"],

  GP: ["Johannesburg", "Pretoria", "Sandton", "Soweto"],
  WC: ["Cape Town", "Paarl", "Stellenbosch"],
  KZN: ["Durban", "Pietermaritzburg", "Richards Bay"],
  EC_ZA: ["East London", "Port Elizabeth"],
  FS: ["Bloemfontein"],
  LP: ["Polokwane"],
  NW_ZA: ["Rustenburg"],

  SEL: ["Seoul"],
  PUS: ["Busan"],
  ICN: ["Incheon"],
  GGD: ["Goyang", "Seongnam", "Suwon", "Yongin"],
  DGU: ["Daegu"],
  DJN: ["Daejeon"],
  GWJ: ["Gwangju"],

  BJ_CN: ["Beijing"],
  SH_CN: ["Shanghai"],
  GD_CN: ["Dongguan", "Foshan", "Guangzhou", "Shenzhen", "Zhuhai"],
  ZJ_CN: ["Hangzhou", "Ningbo", "Wenzhou"],
  JS_CN: ["Nanjing", "Suzhou", "Wuxi"],
  SN_CN: ["Baoji", "Xi'an", "Xianyang"],
  SD_CN: ["Jinan", "Qingdao"],
  HEB: ["Shijiazhuang", "Tangshan"],
  SC_CN: ["Chengdu", "Mianyang"],
  FJ_CN: ["Fuzhou", "Xiamen"],
  HN_CN: ["Changsha", "Zhuzhou"],

  LA_NG: ["Ikeja", "Lagos", "Lekki"],
  ABJ: ["Abuja"],
  KN_NG: ["Kano"],
  RV: ["Port Harcourt"],
  OG: ["Abeokuta"],
  OY: ["Ibadan"],

  NCR: ["Makati", "Manila", "Pasig", "Quezon City", "Taguig"],
  CEB: ["Cebu City", "Lapu-Lapu", "Mandaue"],
  DVO: ["Davao City"],
  ILO_PH: ["Iloilo City"],
  BUL: ["Malolos", "Meycauayan"],
  CAV: ["Bacoor", "Dasmariñas", "Imus"],
  LAG_PH: ["Calamba", "San Pedro", "Santa Rosa"],

  IST: ["Istanbul"],
  ANK: ["Ankara"],
  IZM: ["Izmir"],
  ANT_TR: ["Antalya"],
  BRS_TR: ["Bursa"],
  ADN: ["Adana"],

  MZ_PL: ["Warsaw"],
  ML_PL: ["Kraków"],
  WP_PL: ["Poznań"],
  DS_PL: ["Wrocław"],
  SL_PL: ["Katowice"],
  PM_PL: ["Gdańsk"],

  BOG: ["Bogotá"],
  ANT_CO: ["Medellín"],
  VAL_CO: ["Cali"],
  ATL_CO: ["Barranquilla"],
  SAN_CO: ["Bucaramanga"],

  CABA: ["Buenos Aires"],
  BA_AR: ["La Plata", "Mar del Plata"],
  COR_AR: ["Córdoba"],
  SFE: ["Rosario", "Santa Fe"],
  MZA: ["Mendoza"],
  TUC: ["San Miguel de Tucumán"],

  AKL: ["Auckland"],
  WGN: ["Wellington"],
  CAN_NZ: ["Christchurch"],
  WKO: ["Hamilton"],
  OTA: ["Dunedin", "Queenstown"],
  BOP: ["Tauranga"],

  RYD: ["Riyadh"],
  MKH: ["Jeddah", "Mecca"],
  ESH_SA: ["Al Khobar", "Dammam", "Dhahran"],
  MDN: ["Madinah"],

  TA: ["Bnei Brak", "Ramat Gan", "Tel Aviv"],
  JM_IL: ["Jerusalem"],
  HFA: ["Haifa"],
  CTR_IL: ["Petah Tikva", "Rishon LeZion"],

  STK: ["Stockholm"],
  VGT: ["Gothenburg"],
  SKN: ["Malmö"],

  OSL: ["Oslo"],
  VKN: ["Bergen"],
  TRO_NO: ["Trondheim"],

  CPH: ["Copenhagen"],
  SDK: ["Odense"],
  MDJ: ["Aarhus"],

  DUB: ["Dublin"],
  CRK: ["Cork"],
  GAL_IE: ["Galway"],
  LMK: ["Limerick"],

  SG_C: ["Singapore Central"],
  SG_N: ["Woodlands", "Yishun"],
  SG_E: ["Bedok", "Tampines"],
  SG_W: ["Clementi", "Jurong"],
  SG_NE: ["Punggol", "Sengkang"],

  HKI: ["Causeway Bay", "Central", "Wan Chai"],
  KLN: ["Kowloon Bay", "Mong Kok", "Tsim Sha Tsui"],
  NTR: ["Sha Tin", "Tsuen Wan", "Tuen Mun"],

  MOW: ["Moscow"],
  SPE: ["Saint Petersburg"],
  NVS: ["Novosibirsk"],
  SVE: ["Yekaterinburg"],
  KDA: ["Krasnodar", "Sochi"],
  TAT: ["Kazan"],

  PB_PK: ["Faisalabad", "Lahore", "Rawalpindi"],
  SD_PK: ["Karachi"],
  ICT: ["Islamabad"],
  KP_PK: ["Peshawar"],

  DHK: ["Dhaka"],
  CHT: ["Chittagong"],
  KHU: ["Khulna"],
  RAJ_BD: ["Rajshahi"],
  SYL: ["Sylhet"],

  CAI: ["Cairo"],
  ALX: ["Alexandria"],
  GZ_EG: ["Giza"],
  LUX: ["Luxor"],

  NRB: ["Nairobi"],
  CST_KE: ["Mombasa"],
  RVP: ["Nakuru"],

  GAR: ["Accra", "Tema"],
  ASH: ["Kumasi"],

  DOH: ["Doha"],
  RYN: ["Al Rayyan"],

  KWT: ["Kuwait City"],
  AHM: ["Ahmadi"],

  WIE: ["Vienna"],
  STM: ["Graz"],
  OOE: ["Linz"],
  SBG: ["Salzburg"],
  TIR: ["Innsbruck"],

  LIS: ["Lisbon"],
  PRT: ["Porto"],
  FAR_PT: ["Faro"],

  ATT: ["Athens", "Piraeus"],
  CMC: ["Thessaloniki"],
  CRE: ["Heraklion"],

  BUC: ["Bucharest"],
  CLJ: ["Cluj-Napoca"],
  TIM: ["Timișoara"],

  BUD: ["Budapest"],
  PES: ["Debrecen"],

  PHA: ["Prague"],
  JMK: ["Brno"],

  BKK: ["Bangkok"],
  CNX: ["Chiang Mai"],
  PKT: ["Phuket"],

  KUL: ["Kuala Lumpur"],
  SGR: ["Shah Alam"],
  PNG: ["George Town"],
  JHR: ["Johor Bahru"],

  JK: ["Jakarta"],
  JI: ["Bandung"],
  JT: ["Semarang"],
  JB: ["Surabaya"],
  BA_ID: ["Denpasar"],

  HAN: ["Hanoi"],
  HCM: ["Ho Chi Minh City"],
  DAN: ["Da Nang"],

  KBP: ["Kyiv"],
  LWO: ["Lviv"],
  ODS: ["Odesa"],

  LIM: ["Lima"],
  CUS: ["Cusco"],
  ARE_PE: ["Arequipa"],

  RM: ["Santiago"],
  VAP: ["Valparaíso", "Viña del Mar"],
  BIO: ["Concepción"],

  SJ_CR: ["San José"],
  PAN: ["Panama City"],
  KNG: ["Kingston"],
  SAN_JM: ["Saint Andrew"],
  POS: ["Port of Spain"],
  SFD: ["San Fernando"],

  HEL: ["Espoo", "Helsinki", "Vantaa"],
  PIR: ["Tampere"],

  BRU: ["Brussels"],
  FLA: ["Antwerp", "Ghent"],
  WAL: ["Liège", "Namur"],

  TPE: ["Taipei"],
  KHH: ["Kaohsiung"],
  TNN: ["Tainan"],

  MOS: ["Khimki", "Krasnogorsk", "Mytishchi", "Podolsk"],
  BA_PK: ["Quetta"],
  BAR: ["Barisal"],
  CEN_KE: ["Nyeri", "Thika"],
  BGL: ["Eisenstadt"],
  KTN: ["Klagenfurt"],
  NOE: ["Krems", "Sankt Pölten", "Wiener Neustadt"],
  VBG: ["Bregenz", "Dornbirn"],
  AZO: ["Ponta Delgada"],
  MAD_PT: ["Funchal"],
  THS: ["Larissa", "Volos"],
  CON_RO: ["Constanța"],
  SBH: ["Kota Kinabalu"],
  SRW: ["Kuching", "Miri"],
  ASR: ["Abha", "Khamis Mushait"],
  NTH_IL: ["Acre", "Nahariya", "Nazareth"],
  STH_IL: ["Ashdod", "Beer Sheva", "Eilat"],

  DC_VE: ["Caracas"],
  ANZ: ["Barcelona", "Puerto la Cruz"],
  CAR: ["Valencia"],
  BOL_VE: ["Ciudad Bolívar", "Puerto Ordaz"],
  MIR: ["Los Teques", "Petare"],
  ZUL: ["Cabimas", "Maracaibo"],
  BEN: ["Trinidad"],
  CBB: ["Cochabamba"],
  LP_BO: ["El Alto", "La Paz"],
  OR_BO: ["Oruro"],
  POT: ["Potosí"],
  SCZ: ["Santa Cruz de la Sierra"],
  TJA: ["Tarija"],
  AZU: ["Cuenca"],
  ELO: ["Machala"],
  GUA_EC: ["Guayaquil", "Samborondón"],
  IMB: ["Ibarra"],
  MAN_EC: ["Manta", "Portoviejo"],
  PIC: ["Quito"],
  TUN: ["Ambato"],
  APA: ["Ciudad del Este"],
  ASU: ["Asunción"],
  CEN_PY: ["Fernando de la Mora", "Luque", "San Lorenzo"],
  COR_PY: ["Caacupé"],
  ITA: ["Encarnación"],
  MIS_PY: ["San Ignacio"],
  CAN_UY: ["Canelones", "Las Piedras"],
  COL_UY: ["Colonia del Sacramento"],
  MAL_UY: ["Maldonado", "Punta del Este"],
  MON_UY: ["Montevideo"],
  SJO_UY: ["San José de Mayo"],
  ESC: ["Escuintla"],
  GUA_GT: ["Guatemala City", "Mixco", "Villa Nueva"],
  IZA: ["Puerto Barrios"],
  QUE_GT: ["Quetzaltenango"],
  SAC: ["Antigua Guatemala"],
  CHO: ["Choluteca"],
  COR_HN: ["San Pedro Sula"],
  FM_HN: ["Tegucigalpa"],
  OLN: ["Juticalpa"],
  YOR: ["El Progreso"],
  LIB: ["Santa Tecla"],
  SAM: ["San Miguel"],
  SAN_SV: ["Santa Ana"],
  SON_SV: ["Sonsonate"],
  SS_SV: ["San Salvador", "Soyapango"],
  CHI_NI: ["Chinandega"],
  GRA: ["Granada"],
  LEO: ["León"],
  MAN_NI: ["Managua"],
  CMT: ["Camagüey"],
  HAB: ["Havana"],
  HOL: ["Holguín"],
  SCU: ["Santiago de Cuba"],
  VCL: ["Santa Clara"],
  DIS_DO: ["Santo Domingo"],
  LAR_DO: ["La Romana"],
  SDO: ["Santo Domingo Este"],
  SPM: ["San Pedro de Macorís"],
  STO_DO: ["Santiago de los Caballeros"],
  ARB: ["Gonaïves", "Saint-Marc"],
  CEN_HT: ["Hinche"],
  NRD: ["Cap-Haïtien"],
  OUE: ["Port-au-Prince"],
  BAY_PR: ["Bayamón"],
  CAG: ["Caguas"],
  CAR_PR: ["Carolina"],
  PON_PR: ["Ponce"],
  SJN: ["San Juan"],

  ADD: ["Addis Ababa"],
  AMH: ["Bahir Dar", "Gondar"],
  DIR_ET: ["Dire Dawa"],
  ORM: ["Adama", "Jimma"],
  SNK: ["Hawassa"],
  SOM_ET: ["Jigjiga"],
  TGR: ["Mekele"],
  ARU: ["Arusha"],
  DAR: ["Dar es Salaam"],
  DOD: ["Dodoma"],
  MBY: ["Mbeya"],
  MOR_TZ: ["Morogoro"],
  MWA: ["Mwanza"],
  TAN_TZ: ["Tanga"],
  ZAN: ["Zanzibar City"],
  CAS: ["Casablanca"],
  FES: ["Fès", "Meknès"],
  MAR_MA: ["Marrakesh"],
  ORI: ["Oujda"],
  RBC: ["Rabat", "Salé"],
  SOU_MA: ["Agadir"],
  TAN_MA: ["Tangier", "Tétouan"],
  ALG: ["Algiers"],
  ANN_DZ: ["Annaba"],
  BLI: ["Blida"],
  CON_DZ: ["Constantine"],
  ORA: ["Oran"],
  SET_DZ: ["Sétif"],
  TLE: ["Tlemcen"],
  BIE: ["Kuito"],
  HUA: ["Huambo"],
  HUI: ["Lubango"],
  LNO: ["Dundo"],
  LUA_AO: ["Luanda"],
  MAL_AO: ["Malanje"],
  ADA: ["Ngaoundéré"],
  CEN_CM: ["Yaoundé"],
  LIT_CM: ["Douala"],
  NOR_CM: ["Bamenda"],
  OUE_CM: ["Bafoussam"],
  SOR_CM: ["Buea"],
  GZA: ["Xai-Xai"],
  INH: ["Inhambane"],
  MAP_MZ: ["Maputo", "Matola"],
  NAM_MZ: ["Nampula"],
  SOF_MZ: ["Beira"],
  ZAM: ["Quelimane"],
  BUL_ZW: ["Bulawayo"],
  HAR_ZW: ["Harare"],
  MAN_ZW: ["Mutare"],
  MAS_ZW: ["Marondera"],
  MID_ZW: ["Gweru"],
  COP: ["Kitwe", "Ndola"],
  EAS_ZM: ["Chipata"],
  LUA_ZM: ["Mansa"],
  LUS_ZM: ["Lusaka"],
  SHE_ZM: ["Livingstone"],
  CEN_UG: ["Entebbe", "Jinja"],
  EAS_UG: ["Mbale"],
  KAM_UG: ["Kampala"],
  NOR_UG: ["Gulu"],
  WES_UG: ["Mbarara"],
  DIO: ["Diourbel", "Touba"],
  DKR: ["Dakar"],
  SEN_LO: ["Saint-Louis"],
  THI: ["Thiès"],
  ZIG: ["Ziguinchor"],
  ABI: ["Abidjan"],
  GOM_CI: ["Divo", "Gagnoa"],
  MEN_CI: ["Man"],
  VBR: ["Bouaké"],
  EAS_RW: ["Rwamagana"],
  KIG: ["Kigali"],
  NOR_RW: ["Musanze"],
  SOU_RW: ["Huye"],
  WES_RW: ["Rubavu"],
  BEN_LY: ["Benghazi"],
  MIS_LY: ["Misrata"],
  TRI_LY: ["Tripoli"],
  KAI_TN: ["Kairouan"],
  SFA: ["Sfax"],
  SOU_TN: ["Sousse"],
  TUN_TN: ["Tunis"],
  GAD: ["Gedaref"],
  KAS_SD: ["Kassala"],
  KHT_SD: ["Khartoum", "Omdurman"],
  POR_SD: ["Port Sudan"],
  GOB: ["Goma"],
  KIN_CD: ["Kinshasa"],
  KIS_CD: ["Kisangani"],
  LUB_CD: ["Lubumbashi"],
  MBU: ["Mbuji-Mayi"],
  BRZ: ["Brazzaville"],
  KIB: ["Dolisie"],
  PLT_CG: ["Pointe-Noire"],
  ERA_NA: ["Swakopmund", "Walvis Bay"],
  KHM_NA: ["Windhoek"],
  OSH_NA: ["Oshakati"],
  KGT: ["Mochudi"],
  NGW: ["Kanye", "Lobatse"],
  SE_BW: ["Gaborone"],
  BLA_MW: ["Blantyre"],
  LIL_MW: ["Lilongwe"],
  MZU_MW: ["Mzuzu"],
  BKO: ["Bamako"],
  KOU: ["Koulikoro"],
  MOP: ["Mopti"],
  SIK_ML: ["Sikasso"],
  CEN_BF: ["Koupéla"],
  HBS: ["Bobo-Dioulasso"],
  PLT_BF: ["Ziniaré"],
  MAR_NE: ["Maradi"],
  NIA_NE: ["Niamey"],
  TAH: ["Tahoua"],
  ZIN_NE: ["Zinder"],

  ANB: ["Ramadi"],
  BGD_IQ: ["Baghdad"],
  BAS_IQ: ["Basra"],
  EBL: ["Erbil"],
  KRB: ["Karbala"],
  NIN: ["Mosul"],
  NJF: ["Najaf"],
  SUL_IQ: ["Sulaymaniyah"],
  AMM_JO: ["Amman"],
  AQB: ["Aqaba"],
  IRL: ["Irbid"],
  ZRQ: ["Zarqa"],
  BEI: ["Beirut"],
  BEK: ["Zahle"],
  MTN: ["Jounieh"],
  NOR_LB: ["Tripoli"],
  SOU_LB: ["Sidon"],
  BAT_NO: ["Sohar"],
  BAT_SO: ["Rustaq"],
  DHO: ["Salalah"],
  MSQ: ["Muscat"],
  ADE_YE: ["Aden"],
  HOD: ["Hudaydah"],
  IBB: ["Ibb"],
  SAN_YE: ["Sana'a"],
  TAI: ["Taiz"],
  AZB_E: ["Tabriz"],
  FAR_IR: ["Shiraz"],
  GIL: ["Rasht"],
  ISF: ["Isfahan"],
  KER_IR: ["Kerman"],
  KHO: ["Mashhad"],
  KHZ: ["Ahvaz"],
  MAZ: ["Sari"],
  TEH: ["Tehran"],
  CAP_BH: ["Manama"],
  CEN_BH: ["Isa Town"],
  MUH: ["Muharraq"],
  NOR_BH: ["Hamad Town"],
  SOU_BH: ["Riffa"],
  GAZ: ["Gaza City"],
  WBK: ["Ramallah"],
  ALE: ["Aleppo"],
  DAM_SY: ["Damascus"],
  HMA: ["Hama"],
  HMS: ["Homs"],
  LAT: ["Latakia"],
  AKT_KZ: ["Aktobe"],
  ALA_KZ: ["Almaty"],
  AST_KZ: ["Astana"],
  KAR_KZ: ["Karaganda"],
  SHM_KZ: ["Shymkent"],
  AND_UZ: ["Andijan"],
  BUK_UZ: ["Bukhara"],
  FAR_UZ: ["Fergana"],
  NAM_UZ: ["Namangan"],
  SAM_UZ: ["Samarkand"],
  TAS_UZ: ["Tashkent"],
  BAK_AZ: ["Baku"],
  GAN_AZ: ["Ganja"],
  SUM_AZ: ["Sumqayit"],
  ARA_AM: ["Artashat"],
  GEG_AM: ["Sevan"],
  SHI_AM: ["Gyumri"],
  YER_AM: ["Yerevan"],
  AJA: ["Batumi"],
  IMR_GE: ["Kutaisi"],
  KVT: ["Rustavi"],
  TBS: ["Tbilisi"],

  AYE: ["Pathein"],
  BAG_MM: ["Bago"],
  MDL: ["Mandalay"],
  NPT: ["Naypyidaw"],
  SAG_MM: ["Monywa", "Sagaing"],
  YGN: ["Yangon"],
  BAG_NP: ["Kathmandu", "Lalitpur"],
  GAB_NP: ["Pokhara"],
  KAR_NP: ["Surkhet"],
  KOS_NP: ["Biratnagar", "Dharan"],
  LUM_NP: ["Butwal", "Dhangadhi"],
  MAD_NP: ["Birgunj", "Janakpur"],
  SUD_NP: ["Nepalgunj"],
  CEN_LK: ["Kandy"],
  EAS_LK: ["Batticaloa", "Trincomalee"],
  NOR_LK: ["Jaffna"],
  NWE_LK: ["Kurunegala", "Negombo"],
  SOU_LK: ["Galle", "Matara"],
  WES_LK: ["Colombo", "Moratuwa"],
  BAL_AF: ["Mazar-i-Sharif"],
  HER_AF: ["Herat"],
  KBL_AF: ["Kabul"],
  KDH: ["Kandahar"],
  NNR: ["Jalalabad"],
  BTB: ["Battambang"],
  KPT_KH: ["Kampot"],
  PNH: ["Phnom Penh"],
  SRP_KH: ["Siem Reap"],
  CHM: ["Pakse"],
  LPB: ["Luang Prabang"],
  SAV_LA: ["Savannakhet"],
  VTE: ["Vientiane"],
  DRK: ["Darkhan"],
  ORK: ["Erdenet"],
  ULN: ["Ulaanbaatar"],
  BSH_KG: ["Bishkek"],
  JAL_KG: ["Jalal-Abad"],
  OSH_KG: ["Osh"],
  DUS_TJ: ["Dushanbe"],
  KHT_TJ: ["Bokhtar"],
  SDA_TJ: ["Khujand"],

  BAN_SK: ["Banská Bystrica"],
  BRA_SK: ["Bratislava"],
  KOS_SK: ["Košice"],
  NIT_SK: ["Nitra"],
  PRE_SK: ["Prešov"],
  TRE_SK: ["Trenčín"],
  TRN_SK: ["Trnava"],
  ZIL_SK: ["Žilina"],
  CEL_SI: ["Celje"],
  KRA_SI: ["Kranj"],
  LJU: ["Ljubljana"],
  MBX: ["Maribor"],
  OSI: ["Osijek"],
  RIJ: ["Rijeka"],
  SPL: ["Split"],
  ZAD: ["Zadar"],
  ZAG_HR: ["Zagreb"],
  BGD_RS: ["Belgrade"],
  NIS_RS: ["Niš"],
  SNI: ["Kragujevac"],
  VOJ: ["Novi Sad"],
  BUR_BG: ["Burgas"],
  PLV: ["Plovdiv"],
  SOF_BG: ["Sofia"],
  STZ: ["Stara Zagora"],
  VAR_BG: ["Varna"],
  HAR_EE: ["Tallinn"],
  IDA_EE: ["Narva"],
  TAR_EE: ["Tartu"],
  DAG_LV: ["Daugavpils"],
  JEL_LV: ["Jelgava"],
  RGA: ["Riga"],
  KAU_LT: ["Kaunas"],
  KLJ: ["Klaipėda"],
  SIA_LT: ["Šiauliai"],
  VIL_LT: ["Vilnius"],
  CAP_IS: ["Reykjavík"],
  SOU_IS: ["Selfoss"],
  WES_IS: ["Akranes"],
  DUR_AL: ["Durrës"],
  SHK_AL: ["Shkodër"],
  TIR_AL: ["Tirana"],
  VLO_AL: ["Vlorë"],
  FBH: ["Mostar", "Tuzla"],
  SAR_BA: ["Sarajevo"],
  SRP_BA: ["Banja Luka"],
  PHN_MK: ["Bitola"],
  SKP: ["Skopje"],
  VRD_MK: ["Veles"],
  BDV: ["Budva", "Kotor"],
  NKS: ["Nikšić"],
  POD: ["Podgorica"],
  BRS_BY: ["Brest"],
  GOM_BY: ["Gomel"],
  GRD_BY: ["Grodno"],
  MIN_BY: ["Minsk"],
  MOG_BY: ["Mogilev"],
  VIT_BY: ["Vitebsk"],
  BAL_MD: ["Bălți"],
  CHI_MD: ["Chișinău"],
  TGH_MD: ["Tiraspol"],
  DIF_LU: ["Differdange"],
  ESH_LU: ["Esch-sur-Alzette"],
  LUX_C: ["Luxembourg City"],
  BKR_MT: ["Birkirkara"],
  SLM_MT: ["Sliema"],
  VAL_MT: ["Valletta"],
};

export function getCountries(): LocationOption[] {
  return COUNTRIES;
}

export function getStates(countryCode: string): LocationOption[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}

export function getCities(stateCode: string): string[] {
  return CITIES_BY_STATE[stateCode] ?? [];
}

export function getStateLabel(countryCode: string): string {
  switch (countryCode) {
    case "US": return "State";
    case "CA": return "Province";
    case "AU": return "State / Territory";
    case "GB": return "Country / Region";
    case "JP": return "Prefecture";
    case "CH": return "Canton";
    case "DE": return "Bundesland";
    case "AT": return "Bundesland";
    case "BR": return "Estado";
    case "MX": return "Estado";
    case "AR": return "Province";
    case "FR": return "Région";
    case "NL": return "Province";
    case "BE": return "Region";
    case "IT": return "Region";
    case "ES": return "Autonomous Community";
    case "RU": return "Oblast / Region";
    case "CN": return "Province / Municipality";
    case "IN": return "State / UT";
    case "BO": return "Department";
    case "CO": return "Department";
    case "EC": return "Province";
    case "PY": return "Department";
    case "UY": return "Department";
    case "VE": return "State";
    case "GT": return "Department";
    case "HN": return "Department";
    case "SV": return "Department";
    case "DO": return "Province";
    case "PE": return "Region";
    case "CL": return "Region";
    case "MA": return "Region";
    case "DZ": return "Wilaya";
    case "ET": return "Region";
    case "IR": return "Province";
    case "KZ": return "Region";
    case "UZ": return "Region";
    case "NP": return "Province";
    case "LK": return "Province";
    case "PL": return "Voivodeship";
    default: return "State / Region";
  }
}

export function findStateCode(countryCode: string, stateLong: string, stateShort?: string): string {
  const states = getStates(countryCode);
  if (states.length === 0) return stateLong || stateShort || "";

  if (stateShort) {
    const byShort = states.find((s) => s.code.toLowerCase() === stateShort.toLowerCase());
    if (byShort) return byShort.code;
    const byShortLabel = states.find((s) => s.label.toLowerCase() === stateShort.toLowerCase());
    if (byShortLabel) return byShortLabel.code;
  }

  if (stateLong) {
    const byCode = states.find((s) => s.code.toLowerCase() === stateLong.toLowerCase());
    if (byCode) return byCode.code;
    const byLabel = states.find((s) => s.label.toLowerCase() === stateLong.toLowerCase());
    if (byLabel) return byLabel.code;
    const partial = states.find((s) => s.label.toLowerCase().startsWith(stateLong.toLowerCase()));
    if (partial) return partial.code;
  }

  return stateLong || stateShort || "";
}
